/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'email' : string,
  'adminName' : string,
  'upiId' : string,
  'mobile' : MobileNumber,
  'qrCodeBlobId' : ExternalBlob,
}
export interface AdminSettingsExtended {
  'pointsPerAd' : bigint,
  'cpagripOfferWallName' : string,
  'cloudinaryApiKey' : string,
  'cpagripApiKey' : string,
  'razorpayKeyId' : string,
  'razorpayKeySecret' : string,
  'gameEnabled' : boolean,
  'referralLevel1Pct' : bigint,
  'referralLevel2Pct' : bigint,
  'referralLevel3Pct' : bigint,
  'referralLevel4Pct' : number,
  'referralLevel5Pct' : number,
  'minWithdrawal' : bigint,
  'upiQrCodeUrl' : string,
  'rewardsEnabled' : boolean,
  'upiId' : string,
  'cloudinaryCloudName' : string,
  'ludoEnabled' : boolean,
  'cpagripWebhookSecret' : string,
  'redemptionRate' : bigint,
  'udhaarBookEnabled' : boolean,
  'cloudinaryApiSecret' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AuditAction = { 'SubscriptionRevoke' : null } |
  { 'WalletDeduct' : null } |
  { 'ProviderReject' : null } |
  { 'SubscriptionAssign' : null } |
  { 'WalletAdd' : null } |
  { 'ProviderApprove' : null } |
  { 'FeatureUnlock' : null } |
  { 'FeatureLock' : null };
export interface AuditLogEntry {
  'id' : string,
  'action' : AuditAction,
  'note' : string,
  'timestamp' : bigint,
  'adminEmail' : string,
  'amount' : [] | [bigint],
  'targetUserId' : string,
}
export interface AutoReply {
  'messages' : Array<string>,
  'userId' : Principal,
  'isEnabled' : boolean,
}
export type Badge = { 'bronze' : null } |
  { 'gold' : null } |
  { 'none' : null } |
  { 'diamond' : null } |
  { 'silver' : null };
export interface Banner {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'linkUrl' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'subtitle' : string,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'emoji' : string,
  'enabled' : boolean,
}
export interface ChatAdminSettings {
  'voiceToTextEnabled' : boolean,
  'storiesEnabled' : boolean,
  'payToUnlockEnabled' : boolean,
  'chatEnabled' : boolean,
  'vanishModeEnabled' : boolean,
  'referralEnabled' : boolean,
  'autoReplyEnabled' : boolean,
  'pointsPerMessage' : bigint,
  'stripeSecretKey' : string,
  'pointsPerLogin' : bigint,
  'shortcutsEnabled' : boolean,
  'pointsPerReferral' : bigint,
  'pointsPerStory' : bigint,
  'rewardPointsEnabled' : boolean,
  'ghostModeEnabled' : boolean,
  'stripePublishableKey' : string,
  'schedulingEnabled' : boolean,
  'studyModeEnabled' : boolean,
  'openAiApiKey' : string,
  'broadcastEnabled' : boolean,
}
export interface ChatMessage {
  'id' : bigint,
  'lockPrice' : [] | [bigint],
  'status' : MessageStatus,
  'content' : string,
  'unlockedBy' : Array<Principal>,
  'deletedForEveryoneAt' : [] | [bigint],
  'lockedFile' : [] | [LockedFile],
  'createdAt' : bigint,
  'deletedForSenderAt' : [] | [bigint],
  'mediaUrl' : [] | [string],
  'messageType' : MessageType,
  'conversationId' : bigint,
  'lockCurrency' : [] | [string],
  'isVanish' : boolean,
  'isLocked' : boolean,
  'replyToId' : [] | [bigint],
  'reactions' : Array<MessageReaction>,
  'senderId' : Principal,
  'scheduledAt' : [] | [bigint],
}
export interface ChatShortcut {
  'id' : bigint,
  'isGlobal' : boolean,
  'content' : string,
  'trigger' : string,
  'createdBy' : ShortcutCreator,
  'category' : ShortcutCategory,
}
export interface ChatStats {
  'totalMessages' : bigint,
  'storiesPosted' : bigint,
  'activeChats' : bigint,
  'totalUsers' : bigint,
}
export interface CommissionConfig {
  'retailerSharePct' : number,
  'adminSharePct' : number,
  'globalCommissionPct' : number,
}
export interface ContentLockerConfig { 'features' : Array<LockedFeature> }
export interface Conversation {
  'id' : bigint,
  'lastMessageAt' : bigint,
  'lastMessageId' : [] | [bigint],
  'isGroup' : boolean,
  'adminIds' : Array<Principal>,
  'createdAt' : bigint,
  'groupPhotoUrl' : [] | [string],
  'participantIds' : Array<Principal>,
  'groupName' : [] | [string],
}
export interface CreatorEarningsSummary {
  'payments' : Array<LockedMessagePayment>,
  'pendingPayouts' : bigint,
  'totalEarnings' : bigint,
}
export interface CryptoCoin {
  'id' : string,
  'isListed' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'coinGeckoId' : string,
  'logoUrl' : string,
  'symbol' : string,
}
export interface CryptoInvestConfig {
  'buyFeePercent' : number,
  'highRiskThreshold' : number,
  'isEnabled' : boolean,
  'referralBonusAmount' : number,
  'maxWithdrawal' : number,
  'minWithdrawal' : number,
  'upiId' : string,
  'referralBonusEnabled' : boolean,
  'qrCodeUrl' : string,
  'sellFeePercent' : number,
  'dailyRewardAmount' : number,
  'isDailyRewardEnabled' : boolean,
}
export interface CryptoTransaction {
  'id' : string,
  'status' : TxStatus,
  'priceAtTime' : [] | [number],
  'feeAmount' : [] | [number],
  'netAmount' : number,
  'userId' : string,
  'createdAt' : bigint,
  'coinSymbol' : [] | [string],
  'adminNote' : [] | [string],
  'updatedAt' : bigint,
  'totalAmount' : number,
  'quantity' : [] | [number],
  'feePercent' : [] | [number],
  'txType' : TxType,
  'coinId' : [] | [string],
}
export interface CryptoWallet {
  'dailyRewardStreak' : bigint,
  'mpinHash' : string,
  'referralCode' : string,
  'balance' : number,
  'mpinLockedUntil' : bigint,
  'userId' : string,
  'mpinFailedAttempts' : bigint,
  'createdAt' : bigint,
  'lastDailyRewardClaimed' : bigint,
  'updatedAt' : bigint,
  'hasCompletedFirstTrade' : boolean,
  'totalWithdrawn' : number,
  'totalDeposited' : number,
  'mpinSetAt' : bigint,
}
export interface CryptoWithdrawal {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userEmail' : string,
  'userId' : string,
  'createdAt' : bigint,
  'adminNote' : [] | [string],
  'upiId' : string,
  'amount' : number,
  'resolvedAt' : [] | [bigint],
}
export interface CustomCode {
  'id' : bigint,
  'title' : string,
  'placement' : string,
  'layoutStyle' : string,
  'code' : string,
  'icon' : string,
  'name' : string,
  'enabled' : boolean,
  'btnLabel' : string,
  'alignment' : string,
  'subtitle1' : string,
  'subtitle2' : string,
}
export interface CustomSection {
  'id' : bigint,
  'placement' : string,
  'name' : string,
  'createdAt' : bigint,
  'heading' : string,
  'enabled' : boolean,
  'buttons' : string,
}
export interface DepositRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : string,
  'screenshotUrl' : [] | [string],
  'createdAt' : bigint,
  'rejectionReason' : [] | [string],
  'adminNote' : [] | [string],
  'utrNumber' : string,
  'amount' : number,
  'resolvedAt' : [] | [bigint],
}
export type ExternalBlob = Uint8Array;
export interface JobItem {
  'id' : bigint,
  'title' : string,
  'applyLink' : string,
  'createdAt' : bigint,
  'enabled' : boolean,
  'category' : string,
  'department' : string,
  'lastDate' : string,
  'location' : string,
}
export interface LeaderboardEntry {
  'displayName' : string,
  'userId' : Principal,
  'points' : bigint,
}
export interface LocalNewsItem {
  'id' : bigint,
  'title' : string,
  'postedBy' : Principal,
  'content' : string,
  'createdAt' : bigint,
  'imageUrl' : [] | [string],
}
export type LockType = { 'password' : null } |
  { 'none' : null } |
  { 'task' : null };
export interface LockedFeature {
  'id' : string,
  'createdAt' : bigint,
  'secretKeyHash' : string,
  'cpaOfferLink' : string,
  'updatedAt' : bigint,
  'isLocked' : boolean,
  'featureName' : string,
}
export interface LockedFile {
  'unlockedBy' : Array<Principal>,
  'task' : [] | [LockedFileTask],
  'lockType' : LockType,
  'passwordHash' : [] | [string],
  'fileUrl' : string,
}
export interface LockedFileTask { 'question' : string, 'answer' : string }
export interface LockedMessagePayment {
  'id' : bigint,
  'status' : LockedMessageStatus,
  'unlockedAt' : [] | [bigint],
  'messageId' : string,
  'createdAt' : bigint,
  'creatorId' : Principal,
  'upiTxnRef' : [] | [string],
  'currency' : string,
  'buyerId' : Principal,
  'stripePaymentIntentId' : [] | [string],
  'amount' : bigint,
}
export type LockedMessageStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type MarketCategory = { 'vehicles' : null } |
  { 'other' : null } |
  { 'jobs' : null } |
  { 'property' : null } |
  { 'mobile' : null } |
  { 'services' : null } |
  { 'electronics' : null };
export interface MarketListing {
  'id' : bigint,
  'title' : string,
  'photoUrls' : Array<string>,
  'expiresAt' : [] | [bigint],
  'city' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'whatsappContact' : string,
  'isFeatured' : boolean,
  'category' : MarketCategory,
  'sellerId' : Principal,
  'price' : bigint,
}
export interface MessageReaction {
  'userIds' : Array<Principal>,
  'emoji' : string,
}
export type MessageStatus = { 'read' : null } |
  { 'sent' : null } |
  { 'delivered' : null };
export type MessageType = { 'voiceText' : null } |
  { 'youtubeLink' : null } |
  { 'file' : null } |
  { 'text' : null } |
  { 'locked' : null } |
  { 'scheduledMessage' : null } |
  { 'image' : null } |
  { 'reply' : null } |
  { 'reaction' : null };
export type MobileNumber = string;
export interface NewsItem {
  'id' : bigint,
  'title' : string,
  'link' : string,
  'createdAt' : bigint,
  'enabled' : boolean,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : string,
  'ownerId' : Principal,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface OfferTransaction {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'reversed' : null } |
    { 'credited' : null },
  'offerUserId' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'txType' : { 'manualCredit' : null } |
    { 'referralBonus' : null } |
    { 'cpalead' : null },
  'amount' : bigint,
}
export interface OfferUser {
  'id' : bigint,
  'tier5Earnings' : bigint,
  'referralCode' : string,
  'tier4Earnings' : bigint,
  'userId' : string,
  'createdAt' : bigint,
  'pendingEarnings' : bigint,
  'tier3Earnings' : bigint,
  'email' : string,
  'referredBy' : [] | [string],
  'tier2Earnings' : bigint,
  'passwordHash' : string,
  'totalEarnings' : bigint,
  'mobile' : [] | [string],
  'tier1Earnings' : bigint,
}
export interface OfferWithdrawal {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'paid' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'offerUserId' : bigint,
  'processedAt' : [] | [bigint],
  'adminNote' : [] | [string],
  'upiId' : string,
  'amount' : bigint,
  'requestedAt' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'orderType' : string,
  'imageUrl' : [] | [string],
  'customerId' : bigint,
  'providerId' : bigint,
}
export interface PaymentConfig {
  'razorpayKeyId' : string,
  'razorpayKeySecret' : string,
  'upiVpa' : string,
  'qrCodeUrl' : string,
}
export type PaymentMethod = { 'upi' : null } |
  { 'stripe' : null };
export type PlanType = { 'pending' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface PointsHistoryEntry {
  'at' : bigint,
  'action' : string,
  'points' : bigint,
}
export interface PortfolioHolding {
  'id' : string,
  'userId' : string,
  'coinSymbol' : string,
  'totalCost' : number,
  'updatedAt' : bigint,
  'coinName' : string,
  'quantity' : number,
  'coinId' : string,
  'avgBuyPrice' : number,
}
export type PremiumPlan = { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export interface PremiumPrices {
  'annual' : bigint,
  'quarterly' : bigint,
  'monthly' : bigint,
}
export interface PremiumSubscription {
  'startedAt' : bigint,
  'paymentMethod' : PaymentMethod,
  'expiresAt' : bigint,
  'stripeSubscriptionId' : [] | [string],
  'userId' : Principal,
  'plan' : PremiumPlan,
  'isActive' : boolean,
}
export interface ProviderProfile {
  'userId' : bigint,
  'subscriptionExpiry' : [] | [bigint],
  'subscriptionPlan' : SubscriptionPlan,
  'description' : string,
  'approvalStatus' : ApprovalStatus,
  'subscriptionStatus' : SubscriptionStatus,
  'paymentScreenshotBlobId' : [] | [string],
  'address' : string,
  'serviceRates' : Array<ServiceRate>,
  'upiId' : string,
  'shopName' : string,
  'category' : string,
  'qrCodeBlobId' : [] | [string],
  'planType' : PlanType,
  'photos' : Array<string>,
}
export interface QrEntry {
  'id' : string,
  'qrUrl' : string,
  'isActive' : boolean,
  'qrLabel' : string,
}
export interface RechargeApiConfig {
  'autoRefundEnabled' : boolean,
  'isActive' : boolean,
  'responseParam' : string,
  'apiKey' : string,
  'apiUrl' : string,
}
export interface RechargeReceipt {
  'id' : bigint,
  'txnId' : bigint,
  'netCost' : bigint,
  'userId' : bigint,
  'operator' : string,
  'generatedAt' : bigint,
  'circle' : string,
  'referenceId' : string,
  'commission' : bigint,
  'mobile' : string,
  'amount' : bigint,
}
export interface RechargeTransaction {
  'id' : bigint,
  'status' : string,
  'netCost' : number,
  'userId' : bigint,
  'operator' : string,
  'createdAt' : bigint,
  'circle' : string,
  'commission' : number,
  'mobile' : string,
  'amount' : number,
}
export interface ReferralStats {
  'code' : string,
  'count' : bigint,
  'pointsEarned' : bigint,
  'badge' : string,
}
export interface RewardPoints {
  'userId' : Principal,
  'history' : Array<PointsHistoryEntry>,
  'totalPoints' : bigint,
}
export interface ScheduledMessage {
  'id' : bigint,
  'status' : ScheduledMessageStatus,
  'content' : string,
  'conversationId' : bigint,
  'senderId' : Principal,
  'scheduledAt' : bigint,
}
export type ScheduledMessageStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'sent' : null };
export interface ScrapRate {
  'id' : bigint,
  'ratePerKg' : number,
  'enabled' : boolean,
  'ratePerGram' : number,
  'itemName' : string,
}
export interface ServiceRate {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type ShortcutCategory = { 'custom' : null } |
  { 'greet' : null } |
  { 'business' : null } |
  { 'formula' : null };
export type ShortcutCreator = { 'admin' : null } |
  { 'user' : Principal };
export interface SmsConfig {
  'fast2smsApiKey' : string,
  'isEnabled' : boolean,
  'senderId' : string,
}
export interface StopLossRule {
  'id' : string,
  'quantityToSell' : number,
  'userId' : string,
  'createdAt' : bigint,
  'coinSymbol' : string,
  'limitPriceInr' : number,
  'isActive' : boolean,
  'triggeredAt' : [] | [bigint],
  'coinId' : string,
}
export interface Story {
  'id' : bigint,
  'expiresAt' : bigint,
  'viewerIds' : Array<Principal>,
  'authorId' : Principal,
  'createdAt' : bigint,
  'mediaUrl' : [] | [string],
  'textContent' : [] | [string],
}
export type SubscriptionPlan = { 'twelveMonths' : null } |
  { 'threeMonths' : null } |
  { 'oneMonth' : null };
export interface SubscriptionPricing {
  'threeMonthPrice' : bigint,
  'twelveMonthPrice' : bigint,
  'oneMonthPrice' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface SupportTicket {
  'id' : string,
  'status' : TicketStatus,
  'userEmail' : string,
  'subject' : string,
  'userId' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'category' : TicketCategory,
  'priority' : TicketPriority,
}
export type TicketCategory = { 'coinInquiry' : null } |
  { 'general' : null } |
  { 'withdrawalQuery' : null } |
  { 'bugReport' : null };
export type TicketPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TicketReply {
  'id' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'authorRole' : { 'admin' : null } |
    { 'user' : null },
  'ticketId' : string,
  'message' : string,
}
export type TicketStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type TxStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'pendingApproval' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'failed' : null };
export type TxType = { 'buy' : null } |
  { 'sell' : null } |
  { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'dailyReward' : null };
export interface UdhaarCustomer {
  'id' : string,
  'shopId' : string,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
  'mobile' : string,
}
export interface UdhaarTransaction {
  'id' : string,
  'status' : string,
  'transactionType' : string,
  'shopId' : string,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'customerId' : string,
  'amount' : number,
}
export interface UpiEntry {
  'id' : string,
  'isActive' : boolean,
  'upiName' : string,
  'upiId' : string,
}
export interface UpiPaymentRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'plan' : PremiumPlan,
  'upiTxnRef' : string,
  'amount' : bigint,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'securityQuestion' : string,
  'securityAnswer' : string,
  'passwordHash' : string,
  'mobile' : MobileNumber,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserChatProfile {
  'bio' : [] | [string],
  'referralCode' : string,
  'username' : [] | [string],
  'displayName' : string,
  'city' : [] | [string],
  'userId' : Principal,
  'createdAt' : bigint,
  'referralCount' : bigint,
  'ghostModeEnabled' : boolean,
  'badge' : Badge,
  'studyModeEnabled' : boolean,
  'pointsBalance' : bigint,
  'profilePhotoUrl' : [] | [string],
  'autoReply' : [] | [AutoReply],
  'studyModeSelectedChats' : Array<bigint>,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'role' : UserRole,
  'mobile' : MobileNumber,
}
export type UserRole = { 'admin' : null } |
  { 'provider' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubscription {
  'status' : string,
  'assignedByAdmin' : boolean,
  'endDate' : bigint,
  'userId' : string,
  'startDate' : bigint,
}
export interface VaultItem {
  'id' : bigint,
  'isViewOnce' : boolean,
  'title' : string,
  'expiresAt' : [] | [bigint],
  'ownerId' : Principal,
  'createdAt' : bigint,
  'mediaUrl' : string,
  'viewedAt' : [] | [bigint],
}
export type VerifyKeyResult = { 'ok' : boolean } |
  { 'err' : string };
export interface VideoItem {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'platform' : string,
  'enabled' : boolean,
  'category' : string,
  'videoUrl' : string,
}
export interface WalletTopupRequest {
  'id' : bigint,
  'status' : string,
  'userId' : bigint,
  'note' : string,
  'amount' : number,
  'requestedAt' : bigint,
  'resolvedAt' : [] | [bigint],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateStripePremium' : ActorMethod<
    [PremiumPlan, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addBanner' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addCategory' : ActorMethod<[string, string, string], bigint>,
  'addChatGroupMembers' : ActorMethod<[bigint, Array<Principal>], boolean>,
  'addChatPersonalShortcut' : ActorMethod<
    [string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addChatVaultItem' : ActorMethod<
    [string, string, boolean, [] | [bigint]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addCoin' : ActorMethod<
    [[] | [string], string, string, string, string],
    { 'ok' : CryptoCoin } |
      { 'err' : string }
  >,
  'addCustomCode' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'addCustomSection' : ActorMethod<[string, string, string, string], bigint>,
  'addJob' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  /**
   * / Add a manager by mobile number — admin only.
   * / Managers have restricted access (News, Jobs, Videos).
   */
  'addManager' : ActorMethod<[string], boolean>,
  'addNews' : ActorMethod<[string, string, string, string, string], bigint>,
  'addQrEntry' : ActorMethod<
    [[] | [string], string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addScrapRate' : ActorMethod<[string, number, number], bigint>,
  'addServiceRate' : ActorMethod<[bigint, ServiceRate], undefined>,
  'addShopPhoto' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Add a customer under the calling provider's shop.
   * / shopId is derived from msg.caller — never accepted from the client.
   */
  'addUdhaarCustomer' : ActorMethod<
    [string, string, string],
    { 'ok' : UdhaarCustomer } |
      { 'err' : string }
  >,
  /**
   * / Add a transaction. shopId is derived from caller; customerId must belong to caller.
   */
  'addUdhaarTransaction' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'addUpiEntry' : ActorMethod<
    [[] | [string], string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addVideo' : ActorMethod<[string, string, string, string, string], bigint>,
  /**
   * / Adjust wallet balance for a user by userId (Nat) — admin only.
   * / Alias so both adminAdjustWallet and adjustWalletBalance work.
   */
  'adjustWalletBalance' : ActorMethod<
    [bigint, number, boolean, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAddChatShortcut' : ActorMethod<
    [string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminAddNewsItem' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Directly add or deduct balance for any user — admin only.
   */
  'adminAdjustWallet' : ActorMethod<[bigint, number, boolean, string], boolean>,
  /**
   * / Adjust (add or deduct) a user's wallet balance and log the action — admin only.
   * / Returns the new balance as Int on success.
   */
  'adminAdjustWalletBalance' : ActorMethod<
    [[] | [string], string, bigint, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminApproveCryptoWithdrawal' : ActorMethod<
    [[] | [string], string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveDeposit' : ActorMethod<
    [[] | [string], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveUpiPremium' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Approve a UPI unlock request — admin only.
   */
  'adminApproveUpiUnlock' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Manually assign or revoke a subscription for a user — admin only.
   */
  'adminAssignSubscription' : ActorMethod<
    [[] | [string], string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminBroadcastChatMessage' : ActorMethod<[string], boolean>,
  'adminDeleteChatShortcut' : ActorMethod<[bigint], boolean>,
  'adminDeleteNewsItem' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllCryptoUsers' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<CryptoWallet> } |
      { 'err' : string }
  >,
  'adminGetAllStopLossRules' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<StopLossRule> } |
      { 'err' : string }
  >,
  'adminGetAllTickets' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<SupportTicket> } |
      { 'err' : string }
  >,
  'adminGetAllWithdrawals' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<CryptoWithdrawal> } |
      { 'err' : string }
  >,
  'adminGetChatStats' : ActorMethod<[], ChatStats>,
  'adminGetCryptoStats' : ActorMethod<
    [[] | [string]],
    {
        'ok' : {
          'totalCommissions' : number,
          'totalVolume' : number,
          'totalUsers' : bigint,
          'totalBalance' : number,
        }
      } |
      { 'err' : string }
  >,
  'adminGetUpiPremiumRequests' : ActorMethod<[], Array<UpiPaymentRequest>>,
  /**
   * / Return all pending UPI unlock requests — admin only.
   * / Returns empty array for non-admin callers (never traps).
   */
  'adminGetUpiUnlockRequests' : ActorMethod<[], Array<LockedMessagePayment>>,
  /**
   * / List all Offer Portal users — admin only.
   * / Accepts adminToken for email+password auth flow (anonymous principal friendly).
   * / Returns #ok([users]) for admin, #err("Unauthorized") for non-admin — never traps.
   */
  'adminListOfferUsers' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<OfferUser> } |
      { 'err' : string }
  >,
  /**
   * / List all pending withdrawal requests — admin only.
   * / Accepts adminToken for email+password auth flow.
   * / Returns #ok([withdrawals]) for admin, #err("Unauthorized") for non-admin — never traps.
   */
  'adminListPendingWithdrawals' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<OfferWithdrawal> } |
      { 'err' : string }
  >,
  'adminRejectCryptoWithdrawal' : ActorMethod<
    [[] | [string], string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectDeposit' : ActorMethod<
    [[] | [string], string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectUpiPremium' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Reject a UPI unlock request — admin only.
   */
  'adminRejectUpiUnlock' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminResetMpin' : ActorMethod<
    [[] | [string], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-authenticated direct password reset for an Offer Portal user (no OTP).
   * / callerEmail and callerPasswordHash must match the admin credentials.
   */
  'adminResetOfferPassword' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Resolve a withdrawal request (approve/reject/paid) — admin only.
   * / Accepts adminToken for email+password auth flow.
   * / Returns #ok(true) on success, #err("Unauthorized") for non-admin — never traps.
   */
  'adminResolveWithdrawal' : ActorMethod<
    [
      [] | [string],
      bigint,
      { 'paid' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
      [] | [string],
    ],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminSeedChatDemoData' : ActorMethod<[], boolean>,
  'adminSetPremiumPrices' : ActorMethod<
    [bigint, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveProvider' : ActorMethod<
    [[] | [string], bigint, SubscriptionPlan],
    undefined
  >,
  /**
   * / Approve or reject a topup request.  On approval, funds are credited — admin only.
   */
  'approveTopupRequest' : ActorMethod<[bigint, boolean], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'awardChatPoints' : ActorMethod<[string, bigint], boolean>,
  'blockCryptoUser' : ActorMethod<
    [[] | [string], string, boolean, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'buyCoin' : ActorMethod<
    [string, string, number, number, string],
    { 'ok' : CryptoTransaction } |
      { 'err' : string }
  >,
  'cancelChatScheduledMessage' : ActorMethod<[bigint], boolean>,
  'changeAdminPin' : ActorMethod<[string, string], undefined>,
  'changeMpin' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Validate an admin session token — public query.
   * / Returns true if the token is valid and not expired.
   */
  'checkAdminToken' : ActorMethod<[string], boolean>,
  /**
   * / Called from frontend when a coin price update arrives.
   * / Finds all active stop-loss rules for the coin where limitPrice >= currentPrice,
   * / executes a sell for each (without MPIN — system-triggered), and marks rules as triggered.
   */
  'checkAndExecuteStopLoss' : ActorMethod<
    [string, number],
    { 'triggered' : bigint }
  >,
  'claimDailyReward' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  'cleanupExpiredChatStories' : ActorMethod<[], bigint>,
  'cleanupExpiredChatVaultItems' : ActorMethod<[], bigint>,
  /**
   * / Submit a UPI transaction reference for admin approval to unlock a message.
   */
  'confirmUpiUnlock' : ActorMethod<
    [bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createChatGroup' : ActorMethod<
    [string, Array<Principal>, [] | [string]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createListing' : ActorMethod<
    [string, string, bigint, MarketCategory, string, Array<string>, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createSupportTicket' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : SupportTicket } |
      { 'err' : string }
  >,
  /**
   * / Create a Stripe PaymentIntent for a locked message and return clientSecret.
   */
  'createUnlockPaymentIntent' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteChatMessage' : ActorMethod<[bigint, boolean], boolean>,
  'deleteChatNote' : ActorMethod<[bigint], boolean>,
  'deleteChatShortcut' : ActorMethod<[bigint], boolean>,
  'deleteChatVaultItem' : ActorMethod<[bigint], boolean>,
  'deleteCoin' : ActorMethod<
    [[] | [string], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteCustomCode' : ActorMethod<[bigint], boolean>,
  'deleteCustomSection' : ActorMethod<[bigint], boolean>,
  'deleteJob' : ActorMethod<[bigint], boolean>,
  'deleteListing' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteNews' : ActorMethod<[bigint], boolean>,
  'deleteScrapRate' : ActorMethod<[bigint], boolean>,
  'deleteServiceRate' : ActorMethod<[bigint, string], undefined>,
  'deleteStopLossRule' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Delete a customer and all its transactions. Caller must own the customer.
   */
  'deleteUdhaarCustomer' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Delete a transaction. Caller must own the transaction.
   */
  'deleteUdhaarTransaction' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteVideo' : ActorMethod<[bigint], boolean>,
  'editBanner' : ActorMethod<
    [bigint, string, string, string, string, boolean, bigint],
    undefined
  >,
  'featureListing' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'forgotPassword' : ActorMethod<[MobileNumber, string, string], undefined>,
  'forwardChatMessage' : ActorMethod<
    [bigint, bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'freezeCryptoUser' : ActorMethod<
    [[] | [string], string, boolean, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getActiveBanners' : ActorMethod<[], Array<Banner>>,
  'getActiveChatStories' : ActorMethod<[], Array<Story>>,
  /**
   * / Public query — no auth required. Returns the currently active UPI ID, name, and QR URL.
   */
  'getActivePaymentInfo' : ActorMethod<
    [],
    { 'qrUrl' : string, 'upiName' : string, 'upiId' : string }
  >,
  'getActiveProviders' : ActorMethod<[], Array<ProviderProfile>>,
  /**
   * / Return the most recent `limit` audit log entries — admin only.
   * / Returns empty array if caller is not admin (never traps).
   */
  'getAdminAuditLog' : ActorMethod<
    [[] | [string], bigint],
    Array<AuditLogEntry>
  >,
  'getAdminConfig' : ActorMethod<[], [] | [AdminConfig]>,
  /**
   * / Return all admin settings — readable by any caller so the frontend can
   * / apply toggles and rates without an admin auth round-trip.
   */
  'getAdminSettings' : ActorMethod<[], AdminSettingsExtended>,
  /**
   * / Return the current AdMob configuration — admin only.
   * / Returns empty strings for non-admin callers (never traps).
   */
  'getAdmobConfig' : ActorMethod<
    [],
    {
      'rewardedUnitId' : string,
      'appId' : string,
      'ludoBannerId' : string,
      'ludoInterstitialId' : string,
      'interstitialId' : string,
      'bannerUnitId' : string,
    }
  >,
  /**
   * / Return AdMob unit IDs that are safe for the frontend to use — public.
   * / The App ID is intentionally omitted (only needed native-side).
   */
  'getAdmobConfigPublic' : ActorMethod<
    [],
    {
      'rewardedUnitId' : string,
      'ludoBannerId' : string,
      'ludoInterstitialId' : string,
      'interstitialId' : string,
      'bannerUnitId' : string,
    }
  >,
  'getAllCoins' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<CryptoCoin> } |
      { 'err' : string }
  >,
  'getAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  /**
   * / Return all recharge transactions (master log) — admin only.
   * / Returns empty array for non-admin callers (never traps).
   */
  'getAllRechargeTransactions' : ActorMethod<[], Array<RechargeTransaction>>,
  'getAllToggles' : ActorMethod<[], Array<[string, boolean]>>,
  /**
   * / Return all pending topup requests — admin only.
   * / Returns empty array for non-admin callers (never traps).
   */
  'getAllTopupRequests' : ActorMethod<[], Array<WalletTopupRequest>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Return all wallet balances as (userId, balance) pairs — admin only.
   * / Returns empty array for non-admin callers (never traps).
   */
  'getAllWalletBalances' : ActorMethod<[], Array<[bigint, number]>>,
  'getAppSettings' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getChatAdminSettings' : ActorMethod<[], ChatAdminSettings>,
  'getChatNotes' : ActorMethod<[], Array<Note>>,
  'getChatPointsLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getChatScheduledMessages' : ActorMethod<[], Array<ScheduledMessage>>,
  'getChatShortcuts' : ActorMethod<[], Array<ChatShortcut>>,
  'getChatUserProfile' : ActorMethod<[Principal], [] | [UserChatProfile]>,
  'getChatVaultItems' : ActorMethod<[], Array<VaultItem>>,
  /**
   * / Return Cloudinary cloud name and API key — public query.
   * / The API secret is NEVER returned; it stays server-side only.
   */
  'getCloudinaryConfig' : ActorMethod<
    [],
    { 'cloudName' : string, 'apiKey' : string }
  >,
  /**
   * / Return the current commission config — public.
   */
  'getCommissionConfig' : ActorMethod<[], CommissionConfig>,
  /**
   * / Return the full content-locker configuration (all features).
   */
  'getContentLockerConfig' : ActorMethod<[], ContentLockerConfig>,
  'getConversationMessages' : ActorMethod<
    [bigint, bigint, [] | [bigint]],
    Array<ChatMessage>
  >,
  /**
   * / Return the full CPAGrip settings (apiKey + webhookSecret + offerWallName) — admin only.
   * / Returns empty strings for non-admin callers (never traps).
   */
  'getCpagripSettings' : ActorMethod<
    [[] | [string]],
    { 'webhookSecret' : string, 'offerWallName' : string, 'apiKey' : string }
  >,
  /**
   * / Return the caller's pay-to-unlock creator earnings.
   */
  'getCreatorEarnings' : ActorMethod<[], CreatorEarningsSummary>,
  'getCryptoConfig' : ActorMethod<[[] | [string]], CryptoInvestConfig>,
  'getCryptoConfigPublic' : ActorMethod<[], { 'isEnabled' : boolean }>,
  'getCustomCodes' : ActorMethod<[], Array<CustomCode>>,
  'getCustomSections' : ActorMethod<[], Array<CustomSection>>,
  'getCustomerOrders' : ActorMethod<[bigint], Array<Order>>,
  'getDepositRequests' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<DepositRequest> } |
      { 'err' : string }
  >,
  'getJobs' : ActorMethod<[], Array<JobItem>>,
  'getListedCoins' : ActorMethod<[], Array<CryptoCoin>>,
  'getListings' : ActorMethod<
    [[] | [string], [] | [MarketCategory]],
    Array<MarketListing>
  >,
  'getLockedFileUrl' : ActorMethod<[bigint], [] | [string]>,
  /**
   * / Get all managers — admin only.
   * / Returns empty array for non-admin callers (never traps).
   */
  'getManagers' : ActorMethod<[], Array<string>>,
  'getMyChatConversations' : ActorMethod<[], Array<Conversation>>,
  'getMyChatPoints' : ActorMethod<[], RewardPoints>,
  'getMyChatProfile' : ActorMethod<[], [] | [UserChatProfile]>,
  'getMyChatReferralCode' : ActorMethod<[], string>,
  'getMyChatReferralStats' : ActorMethod<[], ReferralStats>,
  'getMyListings' : ActorMethod<[], Array<MarketListing>>,
  /**
   * / Get Offer Portal transaction history for a user.
   */
  'getMyOfferTransactions' : ActorMethod<[bigint], Array<OfferTransaction>>,
  /**
   * / Get withdrawal requests for an Offer Portal user.
   */
  'getMyOfferWithdrawals' : ActorMethod<[bigint], Array<OfferWithdrawal>>,
  /**
   * / Return the caller's recharge transaction history.
   */
  'getMyRechargeHistory' : ActorMethod<[], Array<RechargeTransaction>>,
  /**
   * / Get all receipts for the calling user.
   */
  'getMyRechargeReceipts' : ActorMethod<[], Array<RechargeReceipt>>,
  'getMySubscription' : ActorMethod<[], [] | [PremiumSubscription]>,
  /**
   * / Return all topup requests submitted by the caller.
   */
  'getMyTopupRequests' : ActorMethod<[], Array<WalletTopupRequest>>,
  /**
   * / Return the caller's wallet balance (0.0 if no wallet yet).
   */
  'getMyWalletBalance' : ActorMethod<[], number>,
  'getNews' : ActorMethod<[], Array<NewsItem>>,
  'getNewsItems' : ActorMethod<[], Array<LocalNewsItem>>,
  /**
   * / Get earnings summary for an Offer Portal user.
   */
  'getOfferEarningsSummary' : ActorMethod<
    [bigint],
    {
      'tier5Earnings' : bigint,
      'referralCode' : string,
      'tier4Earnings' : bigint,
      'pendingEarnings' : bigint,
      'tier3Earnings' : bigint,
      'tier2Earnings' : bigint,
      'totalEarnings' : bigint,
      'tier1Earnings' : bigint,
    }
  >,
  /**
   * / Get Offer Portal global config.
   * / Admin callers: receive full config including API keys and webhook secrets.
   * / Non-admin callers (including anonymous): NEVER TRAP — receive safe public config
   * / with isEnabled and postbackUrl only. API keys and secrets are stripped.
   */
  'getOfferPortalConfig' : ActorMethod<
    [[] | [string]],
    {
      'cpaLeadWebhookSecret' : string,
      'cpagripOfferWallName' : string,
      'cpagripApiKey' : string,
      'postbackUrl' : string,
      'adminProfitPct' : bigint,
      'isEnabled' : boolean,
      'isAdmin' : boolean,
      'cpagripWebhookSecret' : string,
      'userProfitPct' : bigint,
    }
  >,
  /**
   * / Get safe Offer Portal config for any user (no auth required) — alias for getOfferPortalConfigPublic.
   * / Returns ONLY non-sensitive fields: isEnabled, adminProfitPct, userProfitPct.
   * / No API keys, no webhook secrets. Never traps for any caller.
   */
  'getOfferPortalConfigForUser' : ActorMethod<
    [],
    {
      'adminProfitPct' : bigint,
      'isEnabled' : boolean,
      'userProfitPct' : bigint,
    }
  >,
  /**
   * / Get the full Offer Portal config including cpagripWebhookSecret and cpagripOfferWallName — admin only.
   * / Use this after saving to verify all 3 CPAGrip fields persisted correctly.
   * / Returns full config for admin, safe empty-secret config for non-admin — never traps.
   */
  'getOfferPortalConfigFull' : ActorMethod<
    [[] | [string]],
    {
        'ok' : {
          'cpaLeadWebhookSecret' : string,
          'cpagripOfferWallName' : string,
          'cpagripApiKey' : string,
          'adminProfitPct' : bigint,
          'isEnabled' : boolean,
          'cpagripWebhookSecret' : string,
          'userProfitPct' : bigint,
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Get Offer Portal global config — public (no auth required).
   * / Returns only non-sensitive fields: isEnabled, cpagripOfferWallUrl, and offerWallName.
   * / Never traps for any caller — safe for anonymous/regular users.
   */
  'getOfferPortalConfigPublic' : ActorMethod<
    [],
    {
      'offerWallName' : string,
      'isEnabled' : boolean,
      'cpagripOfferWallUrl' : string,
    }
  >,
  'getOrCreateChatConversation' : ActorMethod<
    [Principal],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[bigint, string], Array<Order>>,
  /**
   * / Returns the current payment configuration.
   * / Readable by all callers — providers and riders need to display UPI/QR.
   */
  'getPaymentConfig' : ActorMethod<[], PaymentConfig>,
  /**
   * / Alias for getProvidersPendingApproval — kept for frontend compatibility.
   * / Also accepts an adminToken for email+password auth flow.
   */
  'getPendingApprovals' : ActorMethod<[[] | [string]], Array<ProviderProfile>>,
  'getPremiumPlans' : ActorMethod<[], PremiumPrices>,
  'getProviderOrders' : ActorMethod<[bigint], Array<Order>>,
  'getProviderProfile' : ActorMethod<[bigint], [] | [ProviderProfile]>,
  'getProvidersByCategory' : ActorMethod<[string], Array<ProviderProfile>>,
  'getProvidersPendingApproval' : ActorMethod<[], Array<ProviderProfile>>,
  /**
   * / getPublicOfferPortalConfig — FIX 8: public query returning isEnabled + offerWallUrl + offerWallName.
   * / This is the canonical method for portal open/closed check — no admin token required.
   * / Never traps for any caller (anonymous, regular user, admin).
   */
  'getPublicOfferPortalConfig' : ActorMethod<
    [],
    { 'offerWallName' : string, 'isEnabled' : boolean, 'offerWallUrl' : string }
  >,
  'getQrList' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<QrEntry> } |
      { 'err' : string }
  >,
  'getRecentUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Return the current recharge API config — admin only.
   * / Returns default config for non-admin callers (never traps).
   */
  'getRechargeApiConfig' : ActorMethod<[], RechargeApiConfig>,
  /**
   * / Get receipt for a specific recharge transaction.
   */
  'getRechargeReceipt' : ActorMethod<[bigint], [] | [RechargeReceipt]>,
  /**
   * / Return whether recharge service is enabled — public.
   */
  'getRechargeServiceEnabled' : ActorMethod<[], boolean>,
  'getScrapRates' : ActorMethod<[], Array<ScrapRate>>,
  /**
   * / Get SMS (Fast2SMS) config — admin only.
   * / Returns #ok(config) for admin, #ok(empty defaults) for non-admin — never traps.
   */
  'getSmsConfig' : ActorMethod<[], { 'ok' : SmsConfig } | { 'err' : string }>,
  'getSubscriptionPricing' : ActorMethod<[], [] | [SubscriptionPricing]>,
  'getTicketReplies' : ActorMethod<[string], Array<TicketReply>>,
  /**
   * / Return balance for a customer. Caller must own the customer.
   */
  'getUdhaarBalance' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  /**
   * / Return only customers belonging to the calling provider.
   * / shopId is derived from msg.caller — no user-supplied filter accepted.
   */
  'getUdhaarCustomers' : ActorMethod<[], Array<UdhaarCustomer>>,
  /**
   * / Return transactions for a customer. Caller must own the customer.
   */
  'getUdhaarTransactions' : ActorMethod<
    [string],
    { 'ok' : Array<UdhaarTransaction> } |
      { 'err' : string }
  >,
  'getUpiList' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<UpiEntry> } |
      { 'err' : string }
  >,
  'getUserById' : ActorMethod<[bigint], [] | [User]>,
  'getUserByMobile' : ActorMethod<[MobileNumber], [] | [User]>,
  'getUserCryptoTransactions' : ActorMethod<[string], Array<CryptoTransaction>>,
  'getUserCryptoWallet' : ActorMethod<[string], CryptoWallet>,
  'getUserCryptoWithdrawals' : ActorMethod<[string], Array<CryptoWithdrawal>>,
  'getUserDepositRequests' : ActorMethod<[string], Array<DepositRequest>>,
  'getUserPortfolio' : ActorMethod<[string], Array<PortfolioHolding>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStopLossRules' : ActorMethod<[string], Array<StopLossRule>>,
  /**
   * / Get the current subscription status for a given user.
   */
  'getUserSubscriptionStatus' : ActorMethod<[string], [] | [UserSubscription]>,
  'getUserTickets' : ActorMethod<[string], Array<SupportTicket>>,
  'getUsersByRole' : ActorMethod<[UserRole], Array<User>>,
  'getVideos' : ActorMethod<[], Array<VideoItem>>,
  /**
   * / Return wallet balance for any userId — admin only.
   * / Returns 0.0 for non-admin callers (never traps).
   */
  'getWalletBalanceByUserId' : ActorMethod<[bigint], number>,
  /**
   * / Initiate a mobile recharge.  Auto-calculates commission; deducts netCost
   * / from caller's wallet.  Returns new transaction ID.
   */
  'initiateRecharge' : ActorMethod<[string, string, string, number], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  /**
   * / Check if a given mobile number belongs to a manager — public.
   */
  'isManager' : ActorMethod<[string], boolean>,
  'isPremiumUser' : ActorMethod<[[] | [Principal]], boolean>,
  'leaveChatGroup' : ActorMethod<[bigint], boolean>,
  /**
   * / Link an Offer Portal referral code to a crypto wallet so that
   * / when the user completes their first trade the referrer gets a bonus.
   */
  'linkCryptoReferral' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'login' : ActorMethod<
    [MobileNumber, string],
    { 'ok' : User } |
      { 'err' : string }
  >,
  /**
   * / Login to the Offer Portal.
   * / Returns #ok(OfferUser) on success or #err(reason) on bad credentials —
   * / never traps, so the frontend receives a clean error instead of ic0.trap.
   */
  'loginOfferUser' : ActorMethod<
    [string, string],
    { 'ok' : OfferUser } |
      { 'err' : string }
  >,
  /**
   * / loginUser — alias for login, accepts mobile + passwordHash + role (role is ignored, kept for API compat).
   * / Returns #ok(User) or clean error message — never traps.
   */
  'loginUser' : ActorMethod<
    [MobileNumber, string, string],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'markMessagesRead' : ActorMethod<[bigint], boolean>,
  /**
   * / Mark a transaction as paid. Caller must own the transaction.
   */
  'markUdhaarTransactionPaid' : ActorMethod<
    [string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    bigint
  >,
  'postChatStory' : ActorMethod<
    [[] | [string], [] | [string]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'processChatReferralSignup' : ActorMethod<[string], boolean>,
  /**
   * / Process a CPALead postback: verify secret, split profit, credit earnings.
   * / Also triggers 3-tier MLM referral commissions (5%/2%/1%) to ancestors.
   */
  'processCpaLeadPostback' : ActorMethod<[bigint, bigint, string], boolean>,
  'reactToChatMessage' : ActorMethod<[bigint, string], boolean>,
  /**
   * / Refund a Failed recharge — restores netCost to user wallet — admin only.
   */
  'refundRecharge' : ActorMethod<[bigint], boolean>,
  /**
   * / Register a new Offer Portal user (isolated from main user DB).
   * / Returns #ok(OfferUser) on success or #err("already_registered") for duplicate email
   * / so the frontend can show a clean toast instead of a red error code.
   */
  'registerOfferUser' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : OfferUser } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [string, MobileNumber, string, UserRole, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'rejectProvider' : ActorMethod<[[] | [string], bigint], undefined>,
  'removeChatGroupMember' : ActorMethod<[bigint, Principal], boolean>,
  /**
   * / Remove a locked feature by id — admin only.
   */
  'removeLockedFeature' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Remove a manager by mobile number — admin only.
   */
  'removeManager' : ActorMethod<[string], boolean>,
  'removeQrEntry' : ActorMethod<
    [[] | [string], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeShopPhoto' : ActorMethod<[bigint, string], undefined>,
  'removeUpiEntry' : ActorMethod<
    [[] | [string], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'replyToChatStory' : ActorMethod<
    [bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'replyToTicket' : ActorMethod<
    [string, string, string, boolean, [] | [string]],
    { 'ok' : TicketReply } |
      { 'err' : string }
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestCryptoWithdrawal' : ActorMethod<
    [string, string, number, string, string],
    { 'ok' : CryptoWithdrawal } |
      { 'err' : string }
  >,
  'requestDeposit' : ActorMethod<
    [string, number, string, [] | [string]],
    { 'ok' : DepositRequest } |
      { 'err' : string }
  >,
  /**
   * / Request an OTP for Offer Portal password reset.
   * / Stores the OTP in stable memory with a 10-minute TTL.
   * / If the user has a mobile number and Fast2SMS is configured, the SMS is sent.
   * / Otherwise returns ok with instructions to contact admin.
   */
  'requestOfferPasswordReset' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Submit a UPI withdrawal request from the Offer Portal.
   * / Returns #ok(withdrawalId) or #err(reason) — never traps.
   */
  'requestOfferWithdrawal' : ActorMethod<
    [bigint, string, bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Request admin to top-up your wallet.  Returns the new request ID.
   */
  'requestWalletTopup' : ActorMethod<[number, string], bigint>,
  /**
   * / Verify OTP and set a new password for an Offer Portal user.
   * / The OTP must not be expired and must match within 3 attempts.
   */
  'resetOfferPassword' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Alias for updateCpagripSettings — matches frontend method name saveCPAGripKeys.
   * / Saves API key, Webhook Secret, and Offer Wall Name atomically — admin only.
   * / Empty strings are ignored — existing values are preserved, preventing accidental wipe.
   */
  'saveCPAGripKeys' : ActorMethod<
    [[] | [string], string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChatNote' : ActorMethod<
    [string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'scheduleChatMessage' : ActorMethod<
    [bigint, string, bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'searchChatUsers' : ActorMethod<[string], Array<UserChatProfile>>,
  'searchUsers' : ActorMethod<[string], Array<User>>,
  'sellCoin' : ActorMethod<
    [string, string, number, number, string],
    { 'ok' : CryptoTransaction } |
      { 'err' : string }
  >,
  'sendLockedMessage' : ActorMethod<
    [bigint, string, LockType, [] | [string], [] | [LockedFileTask]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<
    [bigint, string, MessageType, [] | [string], [] | [bigint], boolean],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Send a pay-to-unlock message. Receivers must pay lockPrice to read content.
   */
  'sendPayToUnlockMessage' : ActorMethod<
    [bigint, string, bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'setActiveQr' : ActorMethod<
    [[] | [string], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setActiveUpi' : ActorMethod<
    [[] | [string], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setChatAutoReply' : ActorMethod<[boolean, Array<string>], boolean>,
  'setChatGhostMode' : ActorMethod<[boolean], boolean>,
  'setChatStudyMode' : ActorMethod<[boolean, Array<bigint>], boolean>,
  /**
   * / Create or update a locked feature — admin only.
   */
  'setLockedFeature' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setMpin' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Updates the payment configuration (admin only).
   */
  'setPaymentConfig' : ActorMethod<[PaymentConfig], boolean>,
  'setPlanType' : ActorMethod<[bigint, PlanType], undefined>,
  /**
   * / Enable or disable the recharge service — admin only.
   */
  'setRechargeServiceEnabled' : ActorMethod<[boolean], boolean>,
  'setStopLossRule' : ActorMethod<
    [string, string, string, number, number],
    { 'ok' : StopLossRule } |
      { 'err' : string }
  >,
  'submitUpiPremiumRequest' : ActorMethod<
    [PremiumPlan, string, bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Summarize last 50 messages or last 24h messages for a conversation.
   * / Uses OpenAI via HTTP outcall — API key configured in Chat Admin Settings.
   */
  'summarizeChatMessages' : ActorMethod<
    [bigint, { 'last50' : null } | { 'last24h' : null }],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'toggleCustomSection' : ActorMethod<[bigint, boolean], boolean>,
  'unlockMessage' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateAdminConfig' : ActorMethod<[AdminConfig], undefined>,
  /**
   * / Replace ALL admin settings in one atomic call — admin only.
   * / All existing field values are overwritten with the supplied record.
   * / Empty strings for Cloudinary/CPAGrip fields preserve the existing defaults.
   */
  'updateAdminSettings' : ActorMethod<
    [[] | [string], AdminSettingsExtended],
    boolean
  >,
  /**
   * / Update AdMob configuration — admin only.
   */
  'updateAdmobConfig' : ActorMethod<
    [string, string, string, string, string, string],
    boolean
  >,
  'updateAppSettings' : ActorMethod<
    [[] | [string], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCategory' : ActorMethod<
    [bigint, string, string, string, boolean],
    boolean
  >,
  'updateChatAdminSettings' : ActorMethod<[ChatAdminSettings], boolean>,
  'updateChatGroupInfo' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    boolean
  >,
  'updateChatNote' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [string]],
    boolean
  >,
  /**
   * / Update Cloudinary credentials — admin only.
   * / Empty strings preserve existing defaults.
   */
  'updateCloudinaryConfig' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCoin' : ActorMethod<
    [[] | [string], string, boolean],
    { 'ok' : CryptoCoin } |
      { 'err' : string }
  >,
  /**
   * / Update commission config — admin only.
   * / Validates: retailerPct + adminPct must equal globalPct.
   */
  'updateCommissionConfig' : ActorMethod<[number, number, number], boolean>,
  /**
   * / Save the CPAGrip API key in canister state — admin only.
   * / Also mirrors the key into the live offerPortalConfig so it takes effect immediately.
   */
  'updateCpagripApiKey' : ActorMethod<[string], boolean>,
  /**
   * / Save CPAGrip Webhook Secret Key and Offer Wall Name — admin only.
   * / Both fields are persisted in separate stable vars so they survive reloads.
   * / Empty strings are ignored — existing values are preserved.
   */
  'updateCpagripSettings' : ActorMethod<
    [[] | [string], string, string, string],
    boolean
  >,
  'updateCryptoConfig' : ActorMethod<
    [[] | [string], CryptoInvestConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCustomCode' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      boolean,
      string,
      string,
      string,
      string,
      string,
    ],
    boolean
  >,
  'updateCustomSection' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    boolean
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean],
    boolean
  >,
  'updateListing' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [Array<string>],
      [] | [string],
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Update only Ludo / Rewards settings — admin only.
   */
  'updateLudoSettings' : ActorMethod<
    [boolean, boolean, bigint, bigint, bigint],
    boolean
  >,
  'updateMyChatProfile' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string]],
    boolean
  >,
  'updateNews' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  /**
   * / Update Offer Portal config (toggle, offer wall secret, profit split) — admin only.
   * / Also persists cpagripWebhookSecret and cpagripOfferWallName to their stable vars.
   * / Returns #ok(true) on success, #err(reason) if validation fails (e.g. API key too short).
   */
  'updateOfferPortalConfig' : ActorMethod<
    [[] | [string], boolean, string, string, bigint, bigint, string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProviderProfile' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  /**
   * / Extended updateProviderProfile to include upiId and qrCodeBlobId
   */
  'updateProviderProfileFull' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [string]],
    undefined
  >,
  /**
   * / Save recharge API config — admin only.
   */
  'updateRechargeApiConfig' : ActorMethod<
    [string, string, string, boolean, boolean],
    boolean
  >,
  /**
   * / Update the status of a recharge transaction — admin only.
   * / Auto-refund: if status = "Failed" and autoRefundEnabled, automatically refunds netCost.
   * / Receipt: if status = "Success", generates a digital receipt.
   * / SMS: if smsConfig.isEnabled, sends an alert (fire-and-forget).
   */
  'updateRechargeStatus' : ActorMethod<[bigint, string], boolean>,
  /**
   * / Update only the 5-tier referral rates — admin only.
   */
  'updateReferralRates' : ActorMethod<
    [bigint, bigint, bigint, number, number],
    boolean
  >,
  'updateScrapRate' : ActorMethod<
    [bigint, string, number, number, boolean],
    boolean
  >,
  /**
   * / Update SMS config — admin only.
   * / Returns #ok(true) or #err("Unauthorized: Admin only") — never traps.
   */
  'updateSmsConfig' : ActorMethod<
    [string, string, boolean],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Update SMS config with admin token — admin only (alias for email+password auth).
   * / Returns #ok(true) or #err("Unauthorized: Admin only") — never traps.
   */
  'updateSmsConfigWithToken' : ActorMethod<
    [[] | [string], string, string, boolean],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateSubscriptionPricing' : ActorMethod<[SubscriptionPricing], undefined>,
  'updateTicketStatus' : ActorMethod<
    [[] | [string], string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateToggle' : ActorMethod<[[] | [string], string, boolean], undefined>,
  /**
   * / Update a customer. Caller must own the customer (shopId check).
   */
  'updateUdhaarCustomer' : ActorMethod<
    [string, string, string, string],
    { 'ok' : UdhaarCustomer } |
      { 'err' : string }
  >,
  /**
   * / Update a transaction. Caller must own the transaction (shopId check).
   */
  'updateUdhaarTransaction' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'updateVideo' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  'uploadPaymentScreenshot' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Verify admin email+password credentials and issue a 24-hour session token.
   * / The frontend stores this token and passes it as ?adminToken to admin methods.
   * / Returns #ok(token) on success, #err(reason) on failure — never traps.
   */
  'verifyAdminCredentials' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
  /**
   * / Verify a Stripe PaymentIntent and unlock the message if payment succeeded.
   */
  'verifyStripeUnlock' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / User-facing: verify a plain-text unlock key for a named feature.
   */
  'verifyUnlockKey' : ActorMethod<[string, string], VerifyKeyResult>,
  'viewChatStory' : ActorMethod<[bigint], boolean>,
  'viewChatVaultItem' : ActorMethod<[bigint], [] | [VaultItem]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];