/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PremiumPlan = IDL.Variant({
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const ServiceRate = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UdhaarCustomer = IDL.Record({
  'id' : IDL.Text,
  'shopId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UdhaarTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'transactionType' : IDL.Text,
  'shopId' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ChatStats = IDL.Record({
  'totalMessages' : IDL.Nat,
  'storiesPosted' : IDL.Nat,
  'activeChats' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const UpiPaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'plan' : PremiumPlan,
  'upiTxnRef' : IDL.Text,
  'amount' : IDL.Nat,
});
export const LockedMessageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const LockedMessagePayment = IDL.Record({
  'id' : IDL.Nat,
  'status' : LockedMessageStatus,
  'unlockedAt' : IDL.Opt(IDL.Int),
  'messageId' : IDL.Text,
  'createdAt' : IDL.Int,
  'creatorId' : IDL.Principal,
  'upiTxnRef' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'buyerId' : IDL.Principal,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const OfferUser = IDL.Record({
  'id' : IDL.Nat,
  'tier5Earnings' : IDL.Nat,
  'referralCode' : IDL.Text,
  'tier4Earnings' : IDL.Nat,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'pendingEarnings' : IDL.Nat,
  'tier3Earnings' : IDL.Nat,
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'tier2Earnings' : IDL.Nat,
  'passwordHash' : IDL.Text,
  'totalEarnings' : IDL.Nat,
  'tier1Earnings' : IDL.Nat,
});
export const OfferWithdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'offerUserId' : IDL.Nat,
  'processedAt' : IDL.Opt(IDL.Int),
  'adminNote' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const SubscriptionPlan = IDL.Variant({
  'twelveMonths' : IDL.Null,
  'threeMonths' : IDL.Null,
  'oneMonth' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MarketCategory = IDL.Variant({
  'vehicles' : IDL.Null,
  'other' : IDL.Null,
  'jobs' : IDL.Null,
  'property' : IDL.Null,
  'mobile' : IDL.Null,
  'services' : IDL.Null,
  'electronics' : IDL.Null,
});
export const MobileNumber = IDL.Text;
export const Banner = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'linkUrl' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'expiresAt' : IDL.Int,
  'viewerIds' : IDL.Vec(IDL.Principal),
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'textContent' : IDL.Opt(IDL.Text),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PlanType = IDL.Variant({
  'pending' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const ProviderProfile = IDL.Record({
  'userId' : IDL.Nat,
  'subscriptionExpiry' : IDL.Opt(IDL.Int),
  'subscriptionPlan' : SubscriptionPlan,
  'description' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'subscriptionStatus' : SubscriptionStatus,
  'paymentScreenshotBlobId' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'serviceRates' : IDL.Vec(ServiceRate),
  'upiId' : IDL.Text,
  'shopName' : IDL.Text,
  'category' : IDL.Text,
  'qrCodeBlobId' : IDL.Opt(IDL.Text),
  'planType' : PlanType,
  'photos' : IDL.Vec(IDL.Text),
});
export const AuditAction = IDL.Variant({
  'SubscriptionRevoke' : IDL.Null,
  'WalletDeduct' : IDL.Null,
  'ProviderReject' : IDL.Null,
  'SubscriptionAssign' : IDL.Null,
  'WalletAdd' : IDL.Null,
  'ProviderApprove' : IDL.Null,
  'FeatureUnlock' : IDL.Null,
  'FeatureLock' : IDL.Null,
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : AuditAction,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'adminEmail' : IDL.Text,
  'amount' : IDL.Opt(IDL.Int),
  'targetUserId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdminConfig = IDL.Record({
  'email' : IDL.Text,
  'adminName' : IDL.Text,
  'upiId' : IDL.Text,
  'mobile' : MobileNumber,
  'qrCodeBlobId' : ExternalBlob,
});
export const AdminSettingsExtended = IDL.Record({
  'pointsPerAd' : IDL.Nat,
  'cpagripOfferWallName' : IDL.Text,
  'cloudinaryApiKey' : IDL.Text,
  'cpagripApiKey' : IDL.Text,
  'razorpayKeyId' : IDL.Text,
  'razorpayKeySecret' : IDL.Text,
  'gameEnabled' : IDL.Bool,
  'referralLevel1Pct' : IDL.Nat,
  'referralLevel2Pct' : IDL.Nat,
  'referralLevel3Pct' : IDL.Nat,
  'referralLevel4Pct' : IDL.Float64,
  'referralLevel5Pct' : IDL.Float64,
  'minWithdrawal' : IDL.Nat,
  'upiQrCodeUrl' : IDL.Text,
  'rewardsEnabled' : IDL.Bool,
  'upiId' : IDL.Text,
  'cloudinaryCloudName' : IDL.Text,
  'ludoEnabled' : IDL.Bool,
  'cpagripWebhookSecret' : IDL.Text,
  'redemptionRate' : IDL.Nat,
  'udhaarBookEnabled' : IDL.Bool,
  'cloudinaryApiSecret' : IDL.Text,
});
export const RechargeTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'netCost' : IDL.Float64,
  'userId' : IDL.Nat,
  'operator' : IDL.Text,
  'createdAt' : IDL.Int,
  'circle' : IDL.Text,
  'commission' : IDL.Float64,
  'mobile' : IDL.Text,
  'amount' : IDL.Float64,
});
export const WalletTopupRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Nat,
  'note' : IDL.Text,
  'amount' : IDL.Float64,
  'requestedAt' : IDL.Int,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'provider' : IDL.Null,
  'customer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'securityQuestion' : IDL.Text,
  'securityAnswer' : IDL.Text,
  'passwordHash' : IDL.Text,
  'mobile' : MobileNumber,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'mobile' : MobileNumber,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'emoji' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const ChatAdminSettings = IDL.Record({
  'voiceToTextEnabled' : IDL.Bool,
  'storiesEnabled' : IDL.Bool,
  'payToUnlockEnabled' : IDL.Bool,
  'chatEnabled' : IDL.Bool,
  'vanishModeEnabled' : IDL.Bool,
  'referralEnabled' : IDL.Bool,
  'autoReplyEnabled' : IDL.Bool,
  'pointsPerMessage' : IDL.Nat,
  'stripeSecretKey' : IDL.Text,
  'pointsPerLogin' : IDL.Nat,
  'shortcutsEnabled' : IDL.Bool,
  'pointsPerReferral' : IDL.Nat,
  'pointsPerStory' : IDL.Nat,
  'rewardPointsEnabled' : IDL.Bool,
  'ghostModeEnabled' : IDL.Bool,
  'stripePublishableKey' : IDL.Text,
  'schedulingEnabled' : IDL.Bool,
  'studyModeEnabled' : IDL.Bool,
  'openAiApiKey' : IDL.Text,
  'broadcastEnabled' : IDL.Bool,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'points' : IDL.Nat,
});
export const ScheduledMessageStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'sent' : IDL.Null,
});
export const ScheduledMessage = IDL.Record({
  'id' : IDL.Nat,
  'status' : ScheduledMessageStatus,
  'content' : IDL.Text,
  'conversationId' : IDL.Nat,
  'senderId' : IDL.Principal,
  'scheduledAt' : IDL.Int,
});
export const ShortcutCreator = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Principal,
});
export const ShortcutCategory = IDL.Variant({
  'custom' : IDL.Null,
  'greet' : IDL.Null,
  'business' : IDL.Null,
  'formula' : IDL.Null,
});
export const ChatShortcut = IDL.Record({
  'id' : IDL.Nat,
  'isGlobal' : IDL.Bool,
  'content' : IDL.Text,
  'trigger' : IDL.Text,
  'createdBy' : ShortcutCreator,
  'category' : ShortcutCategory,
});
export const Badge = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'none' : IDL.Null,
  'diamond' : IDL.Null,
  'silver' : IDL.Null,
});
export const AutoReply = IDL.Record({
  'messages' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'isEnabled' : IDL.Bool,
});
export const UserChatProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'referralCode' : IDL.Text,
  'username' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'city' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'referralCount' : IDL.Nat,
  'ghostModeEnabled' : IDL.Bool,
  'badge' : Badge,
  'studyModeEnabled' : IDL.Bool,
  'pointsBalance' : IDL.Nat,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
  'autoReply' : IDL.Opt(AutoReply),
  'studyModeSelectedChats' : IDL.Vec(IDL.Nat),
});
export const VaultItem = IDL.Record({
  'id' : IDL.Nat,
  'isViewOnce' : IDL.Bool,
  'title' : IDL.Text,
  'expiresAt' : IDL.Opt(IDL.Int),
  'ownerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'mediaUrl' : IDL.Text,
  'viewedAt' : IDL.Opt(IDL.Int),
});
export const CommissionConfig = IDL.Record({
  'retailerSharePct' : IDL.Float64,
  'adminSharePct' : IDL.Float64,
  'globalCommissionPct' : IDL.Float64,
});
export const LockedFeature = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'secretKeyHash' : IDL.Text,
  'cpaOfferLink' : IDL.Text,
  'updatedAt' : IDL.Int,
  'isLocked' : IDL.Bool,
  'featureName' : IDL.Text,
});
export const ContentLockerConfig = IDL.Record({
  'features' : IDL.Vec(LockedFeature),
});
export const MessageStatus = IDL.Variant({
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'delivered' : IDL.Null,
});
export const LockedFileTask = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const LockType = IDL.Variant({
  'password' : IDL.Null,
  'none' : IDL.Null,
  'task' : IDL.Null,
});
export const LockedFile = IDL.Record({
  'unlockedBy' : IDL.Vec(IDL.Principal),
  'task' : IDL.Opt(LockedFileTask),
  'lockType' : LockType,
  'passwordHash' : IDL.Opt(IDL.Text),
  'fileUrl' : IDL.Text,
});
export const MessageType = IDL.Variant({
  'voiceText' : IDL.Null,
  'youtubeLink' : IDL.Null,
  'file' : IDL.Null,
  'text' : IDL.Null,
  'locked' : IDL.Null,
  'scheduledMessage' : IDL.Null,
  'image' : IDL.Null,
  'reply' : IDL.Null,
  'reaction' : IDL.Null,
});
export const MessageReaction = IDL.Record({
  'userIds' : IDL.Vec(IDL.Principal),
  'emoji' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'lockPrice' : IDL.Opt(IDL.Nat),
  'status' : MessageStatus,
  'content' : IDL.Text,
  'unlockedBy' : IDL.Vec(IDL.Principal),
  'deletedForEveryoneAt' : IDL.Opt(IDL.Int),
  'lockedFile' : IDL.Opt(LockedFile),
  'createdAt' : IDL.Int,
  'deletedForSenderAt' : IDL.Opt(IDL.Int),
  'mediaUrl' : IDL.Opt(IDL.Text),
  'messageType' : MessageType,
  'conversationId' : IDL.Nat,
  'lockCurrency' : IDL.Opt(IDL.Text),
  'isVanish' : IDL.Bool,
  'isLocked' : IDL.Bool,
  'replyToId' : IDL.Opt(IDL.Nat),
  'reactions' : IDL.Vec(MessageReaction),
  'senderId' : IDL.Principal,
  'scheduledAt' : IDL.Opt(IDL.Int),
});
export const CreatorEarningsSummary = IDL.Record({
  'payments' : IDL.Vec(LockedMessagePayment),
  'pendingPayouts' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const CustomCode = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'placement' : IDL.Text,
  'layoutStyle' : IDL.Text,
  'code' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
  'btnLabel' : IDL.Text,
  'alignment' : IDL.Text,
  'subtitle1' : IDL.Text,
  'subtitle2' : IDL.Text,
});
export const CustomSection = IDL.Record({
  'id' : IDL.Nat,
  'placement' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'heading' : IDL.Text,
  'enabled' : IDL.Bool,
  'buttons' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'orderType' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Nat,
  'providerId' : IDL.Nat,
});
export const JobItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'applyLink' : IDL.Text,
  'createdAt' : IDL.Int,
  'enabled' : IDL.Bool,
  'category' : IDL.Text,
  'department' : IDL.Text,
  'lastDate' : IDL.Text,
  'location' : IDL.Text,
});
export const MarketListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'expiresAt' : IDL.Opt(IDL.Int),
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'whatsappContact' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : MarketCategory,
  'sellerId' : IDL.Principal,
  'price' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'lastMessageAt' : IDL.Int,
  'lastMessageId' : IDL.Opt(IDL.Nat),
  'isGroup' : IDL.Bool,
  'adminIds' : IDL.Vec(IDL.Principal),
  'createdAt' : IDL.Int,
  'groupPhotoUrl' : IDL.Opt(IDL.Text),
  'participantIds' : IDL.Vec(IDL.Principal),
  'groupName' : IDL.Opt(IDL.Text),
});
export const PointsHistoryEntry = IDL.Record({
  'at' : IDL.Int,
  'action' : IDL.Text,
  'points' : IDL.Nat,
});
export const RewardPoints = IDL.Record({
  'userId' : IDL.Principal,
  'history' : IDL.Vec(PointsHistoryEntry),
  'totalPoints' : IDL.Nat,
});
export const ReferralStats = IDL.Record({
  'code' : IDL.Text,
  'count' : IDL.Nat,
  'pointsEarned' : IDL.Nat,
  'badge' : IDL.Text,
});
export const OfferTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'reversed' : IDL.Null,
    'credited' : IDL.Null,
  }),
  'offerUserId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'txType' : IDL.Variant({
    'manualCredit' : IDL.Null,
    'referralBonus' : IDL.Null,
    'cpalead' : IDL.Null,
  }),
  'amount' : IDL.Nat,
});
export const RechargeReceipt = IDL.Record({
  'id' : IDL.Nat,
  'txnId' : IDL.Nat,
  'netCost' : IDL.Nat,
  'userId' : IDL.Nat,
  'operator' : IDL.Text,
  'generatedAt' : IDL.Int,
  'circle' : IDL.Text,
  'referenceId' : IDL.Text,
  'commission' : IDL.Nat,
  'mobile' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'stripe' : IDL.Null,
});
export const PremiumSubscription = IDL.Record({
  'startedAt' : IDL.Int,
  'paymentMethod' : PaymentMethod,
  'expiresAt' : IDL.Int,
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'plan' : PremiumPlan,
  'isActive' : IDL.Bool,
});
export const NewsItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'link' : IDL.Text,
  'createdAt' : IDL.Int,
  'enabled' : IDL.Bool,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const LocalNewsItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const PaymentConfig = IDL.Record({
  'razorpayKeyId' : IDL.Text,
  'razorpayKeySecret' : IDL.Text,
  'upiVpa' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
});
export const PremiumPrices = IDL.Record({
  'annual' : IDL.Nat,
  'quarterly' : IDL.Nat,
  'monthly' : IDL.Nat,
});
export const RechargeApiConfig = IDL.Record({
  'autoRefundEnabled' : IDL.Bool,
  'isActive' : IDL.Bool,
  'responseParam' : IDL.Text,
  'apiKey' : IDL.Text,
  'apiUrl' : IDL.Text,
});
export const ScrapRate = IDL.Record({
  'id' : IDL.Nat,
  'ratePerKg' : IDL.Float64,
  'enabled' : IDL.Bool,
  'ratePerGram' : IDL.Float64,
  'itemName' : IDL.Text,
});
export const SmsConfig = IDL.Record({
  'fast2smsApiKey' : IDL.Text,
  'isEnabled' : IDL.Bool,
  'senderId' : IDL.Text,
});
export const SubscriptionPricing = IDL.Record({
  'threeMonthPrice' : IDL.Nat,
  'twelveMonthPrice' : IDL.Nat,
  'oneMonthPrice' : IDL.Nat,
});
export const UserSubscription = IDL.Record({
  'status' : IDL.Text,
  'assignedByAdmin' : IDL.Bool,
  'endDate' : IDL.Int,
  'userId' : IDL.Text,
  'startDate' : IDL.Int,
});
export const VideoItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'platform' : IDL.Text,
  'enabled' : IDL.Bool,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const VerifyKeyResult = IDL.Variant({
  'ok' : IDL.Bool,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateStripePremium' : IDL.Func(
      [PremiumPlan, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addBanner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addChatGroupMembers' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Principal)],
      [IDL.Bool],
      [],
    ),
  'addChatPersonalShortcut' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addChatVaultItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Int)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addCustomCode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addCustomSection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addManager' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addNews' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addScrapRate' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addServiceRate' : IDL.Func([IDL.Nat, ServiceRate], [], []),
  'addShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addUdhaarCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
      [],
    ),
  'addUdhaarTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
      [],
    ),
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adjustWalletBalance' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAddChatShortcut' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminAddNewsItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminAdjustWallet' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminAdjustWalletBalance' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveUpiPremium' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveUpiUnlock' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAssignSubscription' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminBroadcastChatMessage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'adminDeleteChatShortcut' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminDeleteNewsItem' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetChatStats' : IDL.Func([], [ChatStats], ['query']),
  'adminGetUpiPremiumRequests' : IDL.Func(
      [],
      [IDL.Vec(UpiPaymentRequest)],
      ['query'],
    ),
  'adminGetUpiUnlockRequests' : IDL.Func(
      [],
      [IDL.Vec(LockedMessagePayment)],
      ['query'],
    ),
  'adminListOfferUsers' : IDL.Func([], [IDL.Vec(OfferUser)], ['query']),
  'adminListPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(OfferWithdrawal)],
      ['query'],
    ),
  'adminRejectUpiPremium' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectUpiUnlock' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminResolveWithdrawal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'paid' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'adminSeedChatDemoData' : IDL.Func([], [IDL.Bool], []),
  'adminSetPremiumPrices' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveProvider' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat, SubscriptionPlan],
      [],
      [],
    ),
  'approveTopupRequest' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'awardChatPoints' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'cancelChatScheduledMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'changeAdminPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'cleanupExpiredChatStories' : IDL.Func([], [IDL.Nat], []),
  'cleanupExpiredChatVaultItems' : IDL.Func([], [IDL.Nat], []),
  'confirmUpiUnlock' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createChatGroup' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Principal), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        MarketCategory,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createUnlockPaymentIntent' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteBanner' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChatMessage' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'deleteChatNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChatShortcut' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChatVaultItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomCode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomSection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteListing' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteScrapRate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteServiceRate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteUdhaarCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUdhaarTransaction' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'editBanner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'featureListing' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'forgotPassword' : IDL.Func([MobileNumber, IDL.Text, IDL.Text], [], []),
  'forwardChatMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getActiveBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getActiveChatStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getActiveProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'getAdminAuditLog' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(AuditLogEntry)],
      [],
    ),
  'getAdminConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
  'getAdminSettings' : IDL.Func([], [AdminSettingsExtended], ['query']),
  'getAdmobConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'rewardedUnitId' : IDL.Text,
          'appId' : IDL.Text,
          'ludoBannerId' : IDL.Text,
          'ludoInterstitialId' : IDL.Text,
          'interstitialId' : IDL.Text,
          'bannerUnitId' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAdmobConfigPublic' : IDL.Func(
      [],
      [
        IDL.Record({
          'rewardedUnitId' : IDL.Text,
          'ludoBannerId' : IDL.Text,
          'ludoInterstitialId' : IDL.Text,
          'interstitialId' : IDL.Text,
          'bannerUnitId' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'getAllRechargeTransactions' : IDL.Func(
      [],
      [IDL.Vec(RechargeTransaction)],
      ['query'],
    ),
  'getAllToggles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getAllTopupRequests' : IDL.Func(
      [],
      [IDL.Vec(WalletTopupRequest)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllWalletBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getAppSettings' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getChatAdminSettings' : IDL.Func([], [ChatAdminSettings], ['query']),
  'getChatNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getChatPointsLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getChatScheduledMessages' : IDL.Func(
      [],
      [IDL.Vec(ScheduledMessage)],
      ['query'],
    ),
  'getChatShortcuts' : IDL.Func([], [IDL.Vec(ChatShortcut)], ['query']),
  'getChatUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserChatProfile)],
      ['query'],
    ),
  'getChatVaultItems' : IDL.Func([], [IDL.Vec(VaultItem)], ['query']),
  'getCloudinaryConfig' : IDL.Func(
      [],
      [IDL.Record({ 'cloudName' : IDL.Text, 'apiKey' : IDL.Text })],
      ['query'],
    ),
  'getCommissionConfig' : IDL.Func([], [CommissionConfig], ['query']),
  'getContentLockerConfig' : IDL.Func([], [ContentLockerConfig], ['query']),
  'getConversationMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getCpagripSettings' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'webhookSecret' : IDL.Text,
          'offerWallName' : IDL.Text,
          'apiKey' : IDL.Text,
        }),
      ],
      [],
    ),
  'getCreatorEarnings' : IDL.Func([], [CreatorEarningsSummary], ['query']),
  'getCustomCodes' : IDL.Func([], [IDL.Vec(CustomCode)], ['query']),
  'getCustomSections' : IDL.Func([], [IDL.Vec(CustomSection)], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getJobs' : IDL.Func([], [IDL.Vec(JobItem)], ['query']),
  'getListings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(MarketCategory)],
      [IDL.Vec(MarketListing)],
      ['query'],
    ),
  'getLockedFileUrl' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getManagers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyChatConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMyChatPoints' : IDL.Func([], [RewardPoints], ['query']),
  'getMyChatProfile' : IDL.Func([], [IDL.Opt(UserChatProfile)], ['query']),
  'getMyChatReferralCode' : IDL.Func([], [IDL.Text], ['query']),
  'getMyChatReferralStats' : IDL.Func([], [ReferralStats], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(MarketListing)], ['query']),
  'getMyOfferTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OfferTransaction)],
      ['query'],
    ),
  'getMyOfferWithdrawals' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OfferWithdrawal)],
      ['query'],
    ),
  'getMyRechargeHistory' : IDL.Func(
      [],
      [IDL.Vec(RechargeTransaction)],
      ['query'],
    ),
  'getMyRechargeReceipts' : IDL.Func([], [IDL.Vec(RechargeReceipt)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(PremiumSubscription)], ['query']),
  'getMyTopupRequests' : IDL.Func([], [IDL.Vec(WalletTopupRequest)], ['query']),
  'getMyWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getNewsItems' : IDL.Func([], [IDL.Vec(LocalNewsItem)], ['query']),
  'getOfferEarningsSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'tier5Earnings' : IDL.Nat,
          'referralCode' : IDL.Text,
          'tier4Earnings' : IDL.Nat,
          'pendingEarnings' : IDL.Nat,
          'tier3Earnings' : IDL.Nat,
          'tier2Earnings' : IDL.Nat,
          'totalEarnings' : IDL.Nat,
          'tier1Earnings' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOfferPortalConfig' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'cpaLeadWebhookSecret' : IDL.Text,
          'cpagripOfferWallName' : IDL.Text,
          'cpagripApiKey' : IDL.Text,
          'postbackUrl' : IDL.Text,
          'adminProfitPct' : IDL.Nat,
          'isEnabled' : IDL.Bool,
          'isAdmin' : IDL.Bool,
          'cpagripWebhookSecret' : IDL.Text,
          'userProfitPct' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getOfferPortalConfigForUser' : IDL.Func(
      [],
      [
        IDL.Record({
          'adminProfitPct' : IDL.Nat,
          'isEnabled' : IDL.Bool,
          'userProfitPct' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOfferPortalConfigFull' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'cpaLeadWebhookSecret' : IDL.Text,
            'cpagripOfferWallName' : IDL.Text,
            'cpagripApiKey' : IDL.Text,
            'adminProfitPct' : IDL.Nat,
            'isEnabled' : IDL.Bool,
            'cpagripWebhookSecret' : IDL.Text,
            'userProfitPct' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getOfferPortalConfigPublic' : IDL.Func(
      [],
      [
        IDL.Record({
          'adminProfitPct' : IDL.Nat,
          'isEnabled' : IDL.Bool,
          'userProfitPct' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOrCreateChatConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
  'getPendingApprovals' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(ProviderProfile)],
      [],
    ),
  'getPremiumPlans' : IDL.Func([], [PremiumPrices], ['query']),
  'getProviderOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getProviderProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProviderProfile)],
      ['query'],
    ),
  'getProvidersByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'getProvidersPendingApproval' : IDL.Func(
      [],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'getRecentUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getRechargeApiConfig' : IDL.Func([], [RechargeApiConfig], ['query']),
  'getRechargeReceipt' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RechargeReceipt)],
      ['query'],
    ),
  'getRechargeServiceEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getScrapRates' : IDL.Func([], [IDL.Vec(ScrapRate)], ['query']),
  'getSmsConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : SmsConfig, 'err' : IDL.Text })],
      ['query'],
    ),
  'getSubscriptionPricing' : IDL.Func(
      [],
      [IDL.Opt(SubscriptionPricing)],
      ['query'],
    ),
  'getUdhaarBalance' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUdhaarCustomers' : IDL.Func([], [IDL.Vec(UdhaarCustomer)], ['query']),
  'getUdhaarTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UdhaarTransaction), 'err' : IDL.Text })],
      ['query'],
    ),
  'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserByMobile' : IDL.Func([MobileNumber], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscriptionStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserSubscription)],
      ['query'],
    ),
  'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(VideoItem)], ['query']),
  'getWalletBalanceByUserId' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'initiateRecharge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isManager' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isPremiumUser' : IDL.Func([IDL.Opt(IDL.Principal)], [IDL.Bool], ['query']),
  'leaveChatGroup' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'login' : IDL.Func(
      [MobileNumber, IDL.Text],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'loginOfferUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : OfferUser, 'err' : IDL.Text })],
      [],
    ),
  'loginUser' : IDL.Func(
      [MobileNumber, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'markMessagesRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'markUdhaarTransactionPaid' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
      [],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'postChatStory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'processChatReferralSignup' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'processCpaLeadPostback' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'reactToChatMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'refundRecharge' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'registerOfferUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : OfferUser, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, MobileNumber, IDL.Text, UserRole, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'rejectProvider' : IDL.Func([IDL.Opt(IDL.Text), IDL.Nat], [], []),
  'removeChatGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'removeLockedFeature' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeManager' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'replyToChatStory' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'requestOfferWithdrawal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'requestWalletTopup' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Nat], []),
  'saveCPAGripKeys' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveChatNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'scheduleChatMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'searchChatUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserChatProfile)],
      ['query'],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'sendLockedMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, LockType, IDL.Opt(IDL.Text), IDL.Opt(LockedFileTask)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'sendMessage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        MessageType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'sendPayToUnlockMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setChatAutoReply' : IDL.Func([IDL.Bool, IDL.Vec(IDL.Text)], [IDL.Bool], []),
  'setChatGhostMode' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'setChatStudyMode' : IDL.Func([IDL.Bool, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'setLockedFeature' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setPaymentConfig' : IDL.Func([PaymentConfig], [IDL.Bool], []),
  'setPlanType' : IDL.Func([IDL.Nat, PlanType], [], []),
  'setRechargeServiceEnabled' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'submitUpiPremiumRequest' : IDL.Func(
      [PremiumPlan, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'summarizeChatMessages' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'last50' : IDL.Null, 'last24h' : IDL.Null })],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'toggleCustomSection' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'unlockMessage' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateAdminConfig' : IDL.Func([AdminConfig], [], []),
  'updateAdminSettings' : IDL.Func(
      [IDL.Opt(IDL.Text), AdminSettingsExtended],
      [IDL.Bool],
      [],
    ),
  'updateAdmobConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateAppSettings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateChatAdminSettings' : IDL.Func([ChatAdminSettings], [IDL.Bool], []),
  'updateChatGroupInfo' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateChatNote' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateCloudinaryConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCommissionConfig' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateCpagripApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateCpagripSettings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateCustomCode' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateCustomSection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateLudoSettings' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateMyChatProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'updateNews' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateOfferPortalConfig' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProviderProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProviderProfileFull' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateRechargeApiConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateRechargeStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateReferralRates' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateScrapRate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateSmsConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateSubscriptionPricing' : IDL.Func([SubscriptionPricing], [], []),
  'updateToggle' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text, IDL.Bool], [], []),
  'updateUdhaarCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
      [],
    ),
  'updateUdhaarTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
      [],
    ),
  'updateVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'uploadPaymentScreenshot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'verifyAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyStripeUnlock' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyUnlockKey' : IDL.Func([IDL.Text, IDL.Text], [VerifyKeyResult], []),
  'viewChatStory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'viewChatVaultItem' : IDL.Func([IDL.Nat], [IDL.Opt(VaultItem)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PremiumPlan = IDL.Variant({
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const ServiceRate = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UdhaarCustomer = IDL.Record({
    'id' : IDL.Text,
    'shopId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UdhaarTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'transactionType' : IDL.Text,
    'shopId' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ChatStats = IDL.Record({
    'totalMessages' : IDL.Nat,
    'storiesPosted' : IDL.Nat,
    'activeChats' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const UpiPaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'plan' : PremiumPlan,
    'upiTxnRef' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const LockedMessageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const LockedMessagePayment = IDL.Record({
    'id' : IDL.Nat,
    'status' : LockedMessageStatus,
    'unlockedAt' : IDL.Opt(IDL.Int),
    'messageId' : IDL.Text,
    'createdAt' : IDL.Int,
    'creatorId' : IDL.Principal,
    'upiTxnRef' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'buyerId' : IDL.Principal,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const OfferUser = IDL.Record({
    'id' : IDL.Nat,
    'tier5Earnings' : IDL.Nat,
    'referralCode' : IDL.Text,
    'tier4Earnings' : IDL.Nat,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'pendingEarnings' : IDL.Nat,
    'tier3Earnings' : IDL.Nat,
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'tier2Earnings' : IDL.Nat,
    'passwordHash' : IDL.Text,
    'totalEarnings' : IDL.Nat,
    'tier1Earnings' : IDL.Nat,
  });
  const OfferWithdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'offerUserId' : IDL.Nat,
    'processedAt' : IDL.Opt(IDL.Int),
    'adminNote' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const SubscriptionPlan = IDL.Variant({
    'twelveMonths' : IDL.Null,
    'threeMonths' : IDL.Null,
    'oneMonth' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MarketCategory = IDL.Variant({
    'vehicles' : IDL.Null,
    'other' : IDL.Null,
    'jobs' : IDL.Null,
    'property' : IDL.Null,
    'mobile' : IDL.Null,
    'services' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const MobileNumber = IDL.Text;
  const Banner = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'linkUrl' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'expiresAt' : IDL.Int,
    'viewerIds' : IDL.Vec(IDL.Principal),
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'textContent' : IDL.Opt(IDL.Text),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PlanType = IDL.Variant({
    'pending' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const ProviderProfile = IDL.Record({
    'userId' : IDL.Nat,
    'subscriptionExpiry' : IDL.Opt(IDL.Int),
    'subscriptionPlan' : SubscriptionPlan,
    'description' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'subscriptionStatus' : SubscriptionStatus,
    'paymentScreenshotBlobId' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'serviceRates' : IDL.Vec(ServiceRate),
    'upiId' : IDL.Text,
    'shopName' : IDL.Text,
    'category' : IDL.Text,
    'qrCodeBlobId' : IDL.Opt(IDL.Text),
    'planType' : PlanType,
    'photos' : IDL.Vec(IDL.Text),
  });
  const AuditAction = IDL.Variant({
    'SubscriptionRevoke' : IDL.Null,
    'WalletDeduct' : IDL.Null,
    'ProviderReject' : IDL.Null,
    'SubscriptionAssign' : IDL.Null,
    'WalletAdd' : IDL.Null,
    'ProviderApprove' : IDL.Null,
    'FeatureUnlock' : IDL.Null,
    'FeatureLock' : IDL.Null,
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : AuditAction,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'adminEmail' : IDL.Text,
    'amount' : IDL.Opt(IDL.Int),
    'targetUserId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdminConfig = IDL.Record({
    'email' : IDL.Text,
    'adminName' : IDL.Text,
    'upiId' : IDL.Text,
    'mobile' : MobileNumber,
    'qrCodeBlobId' : ExternalBlob,
  });
  const AdminSettingsExtended = IDL.Record({
    'pointsPerAd' : IDL.Nat,
    'cpagripOfferWallName' : IDL.Text,
    'cloudinaryApiKey' : IDL.Text,
    'cpagripApiKey' : IDL.Text,
    'razorpayKeyId' : IDL.Text,
    'razorpayKeySecret' : IDL.Text,
    'gameEnabled' : IDL.Bool,
    'referralLevel1Pct' : IDL.Nat,
    'referralLevel2Pct' : IDL.Nat,
    'referralLevel3Pct' : IDL.Nat,
    'referralLevel4Pct' : IDL.Float64,
    'referralLevel5Pct' : IDL.Float64,
    'minWithdrawal' : IDL.Nat,
    'upiQrCodeUrl' : IDL.Text,
    'rewardsEnabled' : IDL.Bool,
    'upiId' : IDL.Text,
    'cloudinaryCloudName' : IDL.Text,
    'ludoEnabled' : IDL.Bool,
    'cpagripWebhookSecret' : IDL.Text,
    'redemptionRate' : IDL.Nat,
    'udhaarBookEnabled' : IDL.Bool,
    'cloudinaryApiSecret' : IDL.Text,
  });
  const RechargeTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'netCost' : IDL.Float64,
    'userId' : IDL.Nat,
    'operator' : IDL.Text,
    'createdAt' : IDL.Int,
    'circle' : IDL.Text,
    'commission' : IDL.Float64,
    'mobile' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const WalletTopupRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Nat,
    'note' : IDL.Text,
    'amount' : IDL.Float64,
    'requestedAt' : IDL.Int,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'provider' : IDL.Null,
    'customer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'securityQuestion' : IDL.Text,
    'securityAnswer' : IDL.Text,
    'passwordHash' : IDL.Text,
    'mobile' : MobileNumber,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'mobile' : MobileNumber,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'emoji' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const ChatAdminSettings = IDL.Record({
    'voiceToTextEnabled' : IDL.Bool,
    'storiesEnabled' : IDL.Bool,
    'payToUnlockEnabled' : IDL.Bool,
    'chatEnabled' : IDL.Bool,
    'vanishModeEnabled' : IDL.Bool,
    'referralEnabled' : IDL.Bool,
    'autoReplyEnabled' : IDL.Bool,
    'pointsPerMessage' : IDL.Nat,
    'stripeSecretKey' : IDL.Text,
    'pointsPerLogin' : IDL.Nat,
    'shortcutsEnabled' : IDL.Bool,
    'pointsPerReferral' : IDL.Nat,
    'pointsPerStory' : IDL.Nat,
    'rewardPointsEnabled' : IDL.Bool,
    'ghostModeEnabled' : IDL.Bool,
    'stripePublishableKey' : IDL.Text,
    'schedulingEnabled' : IDL.Bool,
    'studyModeEnabled' : IDL.Bool,
    'openAiApiKey' : IDL.Text,
    'broadcastEnabled' : IDL.Bool,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'points' : IDL.Nat,
  });
  const ScheduledMessageStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'sent' : IDL.Null,
  });
  const ScheduledMessage = IDL.Record({
    'id' : IDL.Nat,
    'status' : ScheduledMessageStatus,
    'content' : IDL.Text,
    'conversationId' : IDL.Nat,
    'senderId' : IDL.Principal,
    'scheduledAt' : IDL.Int,
  });
  const ShortcutCreator = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Principal,
  });
  const ShortcutCategory = IDL.Variant({
    'custom' : IDL.Null,
    'greet' : IDL.Null,
    'business' : IDL.Null,
    'formula' : IDL.Null,
  });
  const ChatShortcut = IDL.Record({
    'id' : IDL.Nat,
    'isGlobal' : IDL.Bool,
    'content' : IDL.Text,
    'trigger' : IDL.Text,
    'createdBy' : ShortcutCreator,
    'category' : ShortcutCategory,
  });
  const Badge = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'none' : IDL.Null,
    'diamond' : IDL.Null,
    'silver' : IDL.Null,
  });
  const AutoReply = IDL.Record({
    'messages' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'isEnabled' : IDL.Bool,
  });
  const UserChatProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'referralCode' : IDL.Text,
    'username' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'city' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'referralCount' : IDL.Nat,
    'ghostModeEnabled' : IDL.Bool,
    'badge' : Badge,
    'studyModeEnabled' : IDL.Bool,
    'pointsBalance' : IDL.Nat,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
    'autoReply' : IDL.Opt(AutoReply),
    'studyModeSelectedChats' : IDL.Vec(IDL.Nat),
  });
  const VaultItem = IDL.Record({
    'id' : IDL.Nat,
    'isViewOnce' : IDL.Bool,
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(IDL.Int),
    'ownerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'mediaUrl' : IDL.Text,
    'viewedAt' : IDL.Opt(IDL.Int),
  });
  const CommissionConfig = IDL.Record({
    'retailerSharePct' : IDL.Float64,
    'adminSharePct' : IDL.Float64,
    'globalCommissionPct' : IDL.Float64,
  });
  const LockedFeature = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'secretKeyHash' : IDL.Text,
    'cpaOfferLink' : IDL.Text,
    'updatedAt' : IDL.Int,
    'isLocked' : IDL.Bool,
    'featureName' : IDL.Text,
  });
  const ContentLockerConfig = IDL.Record({
    'features' : IDL.Vec(LockedFeature),
  });
  const MessageStatus = IDL.Variant({
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const LockedFileTask = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const LockType = IDL.Variant({
    'password' : IDL.Null,
    'none' : IDL.Null,
    'task' : IDL.Null,
  });
  const LockedFile = IDL.Record({
    'unlockedBy' : IDL.Vec(IDL.Principal),
    'task' : IDL.Opt(LockedFileTask),
    'lockType' : LockType,
    'passwordHash' : IDL.Opt(IDL.Text),
    'fileUrl' : IDL.Text,
  });
  const MessageType = IDL.Variant({
    'voiceText' : IDL.Null,
    'youtubeLink' : IDL.Null,
    'file' : IDL.Null,
    'text' : IDL.Null,
    'locked' : IDL.Null,
    'scheduledMessage' : IDL.Null,
    'image' : IDL.Null,
    'reply' : IDL.Null,
    'reaction' : IDL.Null,
  });
  const MessageReaction = IDL.Record({
    'userIds' : IDL.Vec(IDL.Principal),
    'emoji' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'lockPrice' : IDL.Opt(IDL.Nat),
    'status' : MessageStatus,
    'content' : IDL.Text,
    'unlockedBy' : IDL.Vec(IDL.Principal),
    'deletedForEveryoneAt' : IDL.Opt(IDL.Int),
    'lockedFile' : IDL.Opt(LockedFile),
    'createdAt' : IDL.Int,
    'deletedForSenderAt' : IDL.Opt(IDL.Int),
    'mediaUrl' : IDL.Opt(IDL.Text),
    'messageType' : MessageType,
    'conversationId' : IDL.Nat,
    'lockCurrency' : IDL.Opt(IDL.Text),
    'isVanish' : IDL.Bool,
    'isLocked' : IDL.Bool,
    'replyToId' : IDL.Opt(IDL.Nat),
    'reactions' : IDL.Vec(MessageReaction),
    'senderId' : IDL.Principal,
    'scheduledAt' : IDL.Opt(IDL.Int),
  });
  const CreatorEarningsSummary = IDL.Record({
    'payments' : IDL.Vec(LockedMessagePayment),
    'pendingPayouts' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const CustomCode = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'placement' : IDL.Text,
    'layoutStyle' : IDL.Text,
    'code' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
    'btnLabel' : IDL.Text,
    'alignment' : IDL.Text,
    'subtitle1' : IDL.Text,
    'subtitle2' : IDL.Text,
  });
  const CustomSection = IDL.Record({
    'id' : IDL.Nat,
    'placement' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'heading' : IDL.Text,
    'enabled' : IDL.Bool,
    'buttons' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'orderType' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Nat,
    'providerId' : IDL.Nat,
  });
  const JobItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'applyLink' : IDL.Text,
    'createdAt' : IDL.Int,
    'enabled' : IDL.Bool,
    'category' : IDL.Text,
    'department' : IDL.Text,
    'lastDate' : IDL.Text,
    'location' : IDL.Text,
  });
  const MarketListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'expiresAt' : IDL.Opt(IDL.Int),
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'whatsappContact' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : MarketCategory,
    'sellerId' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'lastMessageAt' : IDL.Int,
    'lastMessageId' : IDL.Opt(IDL.Nat),
    'isGroup' : IDL.Bool,
    'adminIds' : IDL.Vec(IDL.Principal),
    'createdAt' : IDL.Int,
    'groupPhotoUrl' : IDL.Opt(IDL.Text),
    'participantIds' : IDL.Vec(IDL.Principal),
    'groupName' : IDL.Opt(IDL.Text),
  });
  const PointsHistoryEntry = IDL.Record({
    'at' : IDL.Int,
    'action' : IDL.Text,
    'points' : IDL.Nat,
  });
  const RewardPoints = IDL.Record({
    'userId' : IDL.Principal,
    'history' : IDL.Vec(PointsHistoryEntry),
    'totalPoints' : IDL.Nat,
  });
  const ReferralStats = IDL.Record({
    'code' : IDL.Text,
    'count' : IDL.Nat,
    'pointsEarned' : IDL.Nat,
    'badge' : IDL.Text,
  });
  const OfferTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'reversed' : IDL.Null,
      'credited' : IDL.Null,
    }),
    'offerUserId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'txType' : IDL.Variant({
      'manualCredit' : IDL.Null,
      'referralBonus' : IDL.Null,
      'cpalead' : IDL.Null,
    }),
    'amount' : IDL.Nat,
  });
  const RechargeReceipt = IDL.Record({
    'id' : IDL.Nat,
    'txnId' : IDL.Nat,
    'netCost' : IDL.Nat,
    'userId' : IDL.Nat,
    'operator' : IDL.Text,
    'generatedAt' : IDL.Int,
    'circle' : IDL.Text,
    'referenceId' : IDL.Text,
    'commission' : IDL.Nat,
    'mobile' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({ 'upi' : IDL.Null, 'stripe' : IDL.Null });
  const PremiumSubscription = IDL.Record({
    'startedAt' : IDL.Int,
    'paymentMethod' : PaymentMethod,
    'expiresAt' : IDL.Int,
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'plan' : PremiumPlan,
    'isActive' : IDL.Bool,
  });
  const NewsItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'link' : IDL.Text,
    'createdAt' : IDL.Int,
    'enabled' : IDL.Bool,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const LocalNewsItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const PaymentConfig = IDL.Record({
    'razorpayKeyId' : IDL.Text,
    'razorpayKeySecret' : IDL.Text,
    'upiVpa' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
  });
  const PremiumPrices = IDL.Record({
    'annual' : IDL.Nat,
    'quarterly' : IDL.Nat,
    'monthly' : IDL.Nat,
  });
  const RechargeApiConfig = IDL.Record({
    'autoRefundEnabled' : IDL.Bool,
    'isActive' : IDL.Bool,
    'responseParam' : IDL.Text,
    'apiKey' : IDL.Text,
    'apiUrl' : IDL.Text,
  });
  const ScrapRate = IDL.Record({
    'id' : IDL.Nat,
    'ratePerKg' : IDL.Float64,
    'enabled' : IDL.Bool,
    'ratePerGram' : IDL.Float64,
    'itemName' : IDL.Text,
  });
  const SmsConfig = IDL.Record({
    'fast2smsApiKey' : IDL.Text,
    'isEnabled' : IDL.Bool,
    'senderId' : IDL.Text,
  });
  const SubscriptionPricing = IDL.Record({
    'threeMonthPrice' : IDL.Nat,
    'twelveMonthPrice' : IDL.Nat,
    'oneMonthPrice' : IDL.Nat,
  });
  const UserSubscription = IDL.Record({
    'status' : IDL.Text,
    'assignedByAdmin' : IDL.Bool,
    'endDate' : IDL.Int,
    'userId' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const VideoItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'platform' : IDL.Text,
    'enabled' : IDL.Bool,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const VerifyKeyResult = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateStripePremium' : IDL.Func(
        [PremiumPlan, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addChatGroupMembers' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Principal)],
        [IDL.Bool],
        [],
      ),
    'addChatPersonalShortcut' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addChatVaultItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Int)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addCustomCode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addCustomSection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addManager' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addScrapRate' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addServiceRate' : IDL.Func([IDL.Nat, ServiceRate], [], []),
    'addShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addUdhaarCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
        [],
      ),
    'addUdhaarTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
        [],
      ),
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adjustWalletBalance' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAddChatShortcut' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminAddNewsItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminAdjustWallet' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminAdjustWalletBalance' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveUpiPremium' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveUpiUnlock' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAssignSubscription' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminBroadcastChatMessage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'adminDeleteChatShortcut' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminDeleteNewsItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetChatStats' : IDL.Func([], [ChatStats], ['query']),
    'adminGetUpiPremiumRequests' : IDL.Func(
        [],
        [IDL.Vec(UpiPaymentRequest)],
        ['query'],
      ),
    'adminGetUpiUnlockRequests' : IDL.Func(
        [],
        [IDL.Vec(LockedMessagePayment)],
        ['query'],
      ),
    'adminListOfferUsers' : IDL.Func([], [IDL.Vec(OfferUser)], ['query']),
    'adminListPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(OfferWithdrawal)],
        ['query'],
      ),
    'adminRejectUpiPremium' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectUpiUnlock' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminResolveWithdrawal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'paid' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'adminSeedChatDemoData' : IDL.Func([], [IDL.Bool], []),
    'adminSetPremiumPrices' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveProvider' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat, SubscriptionPlan],
        [],
        [],
      ),
    'approveTopupRequest' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'awardChatPoints' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'cancelChatScheduledMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'changeAdminPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'cleanupExpiredChatStories' : IDL.Func([], [IDL.Nat], []),
    'cleanupExpiredChatVaultItems' : IDL.Func([], [IDL.Nat], []),
    'confirmUpiUnlock' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createChatGroup' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          MarketCategory,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createUnlockPaymentIntent' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteBanner' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChatMessage' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'deleteChatNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChatShortcut' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChatVaultItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomCode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomSection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteScrapRate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteServiceRate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteUdhaarCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUdhaarTransaction' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'editBanner' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'featureListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'forgotPassword' : IDL.Func([MobileNumber, IDL.Text, IDL.Text], [], []),
    'forwardChatMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getActiveBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getActiveChatStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getActiveProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
    'getAdminAuditLog' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Vec(AuditLogEntry)],
        [],
      ),
    'getAdminConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
    'getAdminSettings' : IDL.Func([], [AdminSettingsExtended], ['query']),
    'getAdmobConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'rewardedUnitId' : IDL.Text,
            'appId' : IDL.Text,
            'ludoBannerId' : IDL.Text,
            'ludoInterstitialId' : IDL.Text,
            'interstitialId' : IDL.Text,
            'bannerUnitId' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAdmobConfigPublic' : IDL.Func(
        [],
        [
          IDL.Record({
            'rewardedUnitId' : IDL.Text,
            'ludoBannerId' : IDL.Text,
            'ludoInterstitialId' : IDL.Text,
            'interstitialId' : IDL.Text,
            'bannerUnitId' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
    'getAllRechargeTransactions' : IDL.Func(
        [],
        [IDL.Vec(RechargeTransaction)],
        ['query'],
      ),
    'getAllToggles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getAllTopupRequests' : IDL.Func(
        [],
        [IDL.Vec(WalletTopupRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllWalletBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getAppSettings' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getChatAdminSettings' : IDL.Func([], [ChatAdminSettings], ['query']),
    'getChatNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getChatPointsLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getChatScheduledMessages' : IDL.Func(
        [],
        [IDL.Vec(ScheduledMessage)],
        ['query'],
      ),
    'getChatShortcuts' : IDL.Func([], [IDL.Vec(ChatShortcut)], ['query']),
    'getChatUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserChatProfile)],
        ['query'],
      ),
    'getChatVaultItems' : IDL.Func([], [IDL.Vec(VaultItem)], ['query']),
    'getCloudinaryConfig' : IDL.Func(
        [],
        [IDL.Record({ 'cloudName' : IDL.Text, 'apiKey' : IDL.Text })],
        ['query'],
      ),
    'getCommissionConfig' : IDL.Func([], [CommissionConfig], ['query']),
    'getContentLockerConfig' : IDL.Func([], [ContentLockerConfig], ['query']),
    'getConversationMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getCpagripSettings' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'webhookSecret' : IDL.Text,
            'offerWallName' : IDL.Text,
            'apiKey' : IDL.Text,
          }),
        ],
        [],
      ),
    'getCreatorEarnings' : IDL.Func([], [CreatorEarningsSummary], ['query']),
    'getCustomCodes' : IDL.Func([], [IDL.Vec(CustomCode)], ['query']),
    'getCustomSections' : IDL.Func([], [IDL.Vec(CustomSection)], ['query']),
    'getCustomerOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getJobs' : IDL.Func([], [IDL.Vec(JobItem)], ['query']),
    'getListings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(MarketCategory)],
        [IDL.Vec(MarketListing)],
        ['query'],
      ),
    'getLockedFileUrl' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getManagers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyChatConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMyChatPoints' : IDL.Func([], [RewardPoints], ['query']),
    'getMyChatProfile' : IDL.Func([], [IDL.Opt(UserChatProfile)], ['query']),
    'getMyChatReferralCode' : IDL.Func([], [IDL.Text], ['query']),
    'getMyChatReferralStats' : IDL.Func([], [ReferralStats], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(MarketListing)], ['query']),
    'getMyOfferTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OfferTransaction)],
        ['query'],
      ),
    'getMyOfferWithdrawals' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OfferWithdrawal)],
        ['query'],
      ),
    'getMyRechargeHistory' : IDL.Func(
        [],
        [IDL.Vec(RechargeTransaction)],
        ['query'],
      ),
    'getMyRechargeReceipts' : IDL.Func(
        [],
        [IDL.Vec(RechargeReceipt)],
        ['query'],
      ),
    'getMySubscription' : IDL.Func(
        [],
        [IDL.Opt(PremiumSubscription)],
        ['query'],
      ),
    'getMyTopupRequests' : IDL.Func(
        [],
        [IDL.Vec(WalletTopupRequest)],
        ['query'],
      ),
    'getMyWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getNewsItems' : IDL.Func([], [IDL.Vec(LocalNewsItem)], ['query']),
    'getOfferEarningsSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'tier5Earnings' : IDL.Nat,
            'referralCode' : IDL.Text,
            'tier4Earnings' : IDL.Nat,
            'pendingEarnings' : IDL.Nat,
            'tier3Earnings' : IDL.Nat,
            'tier2Earnings' : IDL.Nat,
            'totalEarnings' : IDL.Nat,
            'tier1Earnings' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOfferPortalConfig' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'cpaLeadWebhookSecret' : IDL.Text,
            'cpagripOfferWallName' : IDL.Text,
            'cpagripApiKey' : IDL.Text,
            'postbackUrl' : IDL.Text,
            'adminProfitPct' : IDL.Nat,
            'isEnabled' : IDL.Bool,
            'isAdmin' : IDL.Bool,
            'cpagripWebhookSecret' : IDL.Text,
            'userProfitPct' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getOfferPortalConfigForUser' : IDL.Func(
        [],
        [
          IDL.Record({
            'adminProfitPct' : IDL.Nat,
            'isEnabled' : IDL.Bool,
            'userProfitPct' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOfferPortalConfigFull' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'cpaLeadWebhookSecret' : IDL.Text,
              'cpagripOfferWallName' : IDL.Text,
              'cpagripApiKey' : IDL.Text,
              'adminProfitPct' : IDL.Nat,
              'isEnabled' : IDL.Bool,
              'cpagripWebhookSecret' : IDL.Text,
              'userProfitPct' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getOfferPortalConfigPublic' : IDL.Func(
        [],
        [
          IDL.Record({
            'adminProfitPct' : IDL.Nat,
            'isEnabled' : IDL.Bool,
            'userProfitPct' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOrCreateChatConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
    'getPendingApprovals' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(ProviderProfile)],
        [],
      ),
    'getPremiumPlans' : IDL.Func([], [PremiumPrices], ['query']),
    'getProviderOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getProviderProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProviderProfile)],
        ['query'],
      ),
    'getProvidersByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'getProvidersPendingApproval' : IDL.Func(
        [],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'getRecentUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getRechargeApiConfig' : IDL.Func([], [RechargeApiConfig], ['query']),
    'getRechargeReceipt' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RechargeReceipt)],
        ['query'],
      ),
    'getRechargeServiceEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getScrapRates' : IDL.Func([], [IDL.Vec(ScrapRate)], ['query']),
    'getSmsConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : SmsConfig, 'err' : IDL.Text })],
        ['query'],
      ),
    'getSubscriptionPricing' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionPricing)],
        ['query'],
      ),
    'getUdhaarBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUdhaarCustomers' : IDL.Func([], [IDL.Vec(UdhaarCustomer)], ['query']),
    'getUdhaarTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UdhaarTransaction), 'err' : IDL.Text })],
        ['query'],
      ),
    'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserByMobile' : IDL.Func([MobileNumber], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscriptionStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserSubscription)],
        ['query'],
      ),
    'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(VideoItem)], ['query']),
    'getWalletBalanceByUserId' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'initiateRecharge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isManager' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isPremiumUser' : IDL.Func([IDL.Opt(IDL.Principal)], [IDL.Bool], ['query']),
    'leaveChatGroup' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'login' : IDL.Func(
        [MobileNumber, IDL.Text],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'loginOfferUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : OfferUser, 'err' : IDL.Text })],
        [],
      ),
    'loginUser' : IDL.Func(
        [MobileNumber, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'markMessagesRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'markUdhaarTransactionPaid' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'postChatStory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'processChatReferralSignup' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'processCpaLeadPostback' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'reactToChatMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'refundRecharge' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'registerOfferUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : OfferUser, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, MobileNumber, IDL.Text, UserRole, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'rejectProvider' : IDL.Func([IDL.Opt(IDL.Text), IDL.Nat], [], []),
    'removeChatGroupMember' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Bool],
        [],
      ),
    'removeLockedFeature' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeManager' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'replyToChatStory' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'requestOfferWithdrawal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'requestWalletTopup' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Nat], []),
    'saveCPAGripKeys' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveChatNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'scheduleChatMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'searchChatUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserChatProfile)],
        ['query'],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'sendLockedMessage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          LockType,
          IDL.Opt(IDL.Text),
          IDL.Opt(LockedFileTask),
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'sendMessage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          MessageType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'sendPayToUnlockMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setChatAutoReply' : IDL.Func(
        [IDL.Bool, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'setChatGhostMode' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'setChatStudyMode' : IDL.Func([IDL.Bool, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'setLockedFeature' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setPaymentConfig' : IDL.Func([PaymentConfig], [IDL.Bool], []),
    'setPlanType' : IDL.Func([IDL.Nat, PlanType], [], []),
    'setRechargeServiceEnabled' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'submitUpiPremiumRequest' : IDL.Func(
        [PremiumPlan, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'summarizeChatMessages' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'last50' : IDL.Null, 'last24h' : IDL.Null })],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'toggleCustomSection' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'unlockMessage' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAdminConfig' : IDL.Func([AdminConfig], [], []),
    'updateAdminSettings' : IDL.Func(
        [IDL.Opt(IDL.Text), AdminSettingsExtended],
        [IDL.Bool],
        [],
      ),
    'updateAdmobConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateAppSettings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateChatAdminSettings' : IDL.Func([ChatAdminSettings], [IDL.Bool], []),
    'updateChatGroupInfo' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateChatNote' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateCloudinaryConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCommissionConfig' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateCpagripApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateCpagripSettings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateCustomCode' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateCustomSection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateLudoSettings' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateMyChatProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateNews' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateOfferPortalConfig' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProviderProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProviderProfileFull' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateRechargeApiConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateRechargeStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateReferralRates' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateScrapRate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateSmsConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateSubscriptionPricing' : IDL.Func([SubscriptionPricing], [], []),
    'updateToggle' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text, IDL.Bool], [], []),
    'updateUdhaarCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
        [],
      ),
    'updateUdhaarTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
        [],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'uploadPaymentScreenshot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'verifyAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyStripeUnlock' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyUnlockKey' : IDL.Func([IDL.Text, IDL.Text], [VerifyKeyResult], []),
    'viewChatStory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'viewChatVaultItem' : IDL.Func([IDL.Nat], [IDL.Opt(VaultItem)], []),
  });
};

export const init = ({ IDL }) => { return []; };