/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceRate = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UdhaarCustomer = IDL.Record({
  'id' : IDL.Text,
  'shopId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UdhaarTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'transactionType' : IDL.Text,
  'shopId' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const OfferUser = IDL.Record({
  'id' : IDL.Nat,
  'referralCode' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'pendingEarnings' : IDL.Nat,
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'passwordHash' : IDL.Text,
  'totalEarnings' : IDL.Nat,
});
export const OfferWithdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'offerUserId' : IDL.Nat,
  'processedAt' : IDL.Opt(IDL.Int),
  'adminNote' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const SubscriptionPlan = IDL.Variant({
  'twelveMonths' : IDL.Null,
  'threeMonths' : IDL.Null,
  'oneMonth' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MobileNumber = IDL.Text;
export const Banner = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'linkUrl' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PlanType = IDL.Variant({
  'pending' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const ProviderProfile = IDL.Record({
  'userId' : IDL.Nat,
  'subscriptionExpiry' : IDL.Opt(IDL.Int),
  'subscriptionPlan' : SubscriptionPlan,
  'description' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'subscriptionStatus' : SubscriptionStatus,
  'paymentScreenshotBlobId' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'serviceRates' : IDL.Vec(ServiceRate),
  'upiId' : IDL.Text,
  'shopName' : IDL.Text,
  'category' : IDL.Text,
  'qrCodeBlobId' : IDL.Opt(IDL.Text),
  'planType' : PlanType,
  'photos' : IDL.Vec(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdminConfig = IDL.Record({
  'email' : IDL.Text,
  'adminName' : IDL.Text,
  'upiId' : IDL.Text,
  'mobile' : MobileNumber,
  'qrCodeBlobId' : ExternalBlob,
});
export const RechargeTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'netCost' : IDL.Float64,
  'userId' : IDL.Nat,
  'operator' : IDL.Text,
  'createdAt' : IDL.Int,
  'circle' : IDL.Text,
  'commission' : IDL.Float64,
  'mobile' : IDL.Text,
  'amount' : IDL.Float64,
});
export const WalletTopupRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Nat,
  'note' : IDL.Text,
  'amount' : IDL.Float64,
  'requestedAt' : IDL.Int,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'provider' : IDL.Null,
  'customer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'securityQuestion' : IDL.Text,
  'securityAnswer' : IDL.Text,
  'passwordHash' : IDL.Text,
  'mobile' : MobileNumber,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'mobile' : MobileNumber,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'emoji' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const CommissionConfig = IDL.Record({
  'retailerSharePct' : IDL.Float64,
  'adminSharePct' : IDL.Float64,
  'globalCommissionPct' : IDL.Float64,
});
export const CustomCode = IDL.Record({
  'id' : IDL.Nat,
  'placement' : IDL.Text,
  'code' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
  'btnLabel' : IDL.Text,
});
export const CustomSection = IDL.Record({
  'id' : IDL.Nat,
  'placement' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'heading' : IDL.Text,
  'enabled' : IDL.Bool,
  'buttons' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'orderType' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Nat,
  'providerId' : IDL.Nat,
});
export const JobItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'applyLink' : IDL.Text,
  'createdAt' : IDL.Int,
  'enabled' : IDL.Bool,
  'category' : IDL.Text,
  'department' : IDL.Text,
  'lastDate' : IDL.Text,
  'location' : IDL.Text,
});
export const OfferTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'reversed' : IDL.Null,
    'credited' : IDL.Null,
  }),
  'offerUserId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'txType' : IDL.Variant({
    'manualCredit' : IDL.Null,
    'referralBonus' : IDL.Null,
    'cpalead' : IDL.Null,
  }),
  'amount' : IDL.Nat,
});
export const RechargeReceipt = IDL.Record({
  'id' : IDL.Nat,
  'txnId' : IDL.Nat,
  'netCost' : IDL.Nat,
  'userId' : IDL.Nat,
  'operator' : IDL.Text,
  'generatedAt' : IDL.Int,
  'circle' : IDL.Text,
  'referenceId' : IDL.Text,
  'commission' : IDL.Nat,
  'mobile' : IDL.Text,
  'amount' : IDL.Nat,
});
export const NewsItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'link' : IDL.Text,
  'createdAt' : IDL.Int,
  'enabled' : IDL.Bool,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const OfferPortalConfig = IDL.Record({
  'cpaLeadWebhookSecret' : IDL.Text,
  'adminProfitPct' : IDL.Nat,
  'isEnabled' : IDL.Bool,
  'userProfitPct' : IDL.Nat,
});
export const RechargeApiConfig = IDL.Record({
  'autoRefundEnabled' : IDL.Bool,
  'isActive' : IDL.Bool,
  'responseParam' : IDL.Text,
  'apiKey' : IDL.Text,
  'apiUrl' : IDL.Text,
});
export const ScrapRate = IDL.Record({
  'id' : IDL.Nat,
  'ratePerKg' : IDL.Float64,
  'enabled' : IDL.Bool,
  'ratePerGram' : IDL.Float64,
  'itemName' : IDL.Text,
});
export const SmsConfig = IDL.Record({
  'fast2smsApiKey' : IDL.Text,
  'isEnabled' : IDL.Bool,
  'senderId' : IDL.Text,
});
export const SubscriptionPricing = IDL.Record({
  'threeMonthPrice' : IDL.Nat,
  'twelveMonthPrice' : IDL.Nat,
  'oneMonthPrice' : IDL.Nat,
});
export const VideoItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'platform' : IDL.Text,
  'enabled' : IDL.Bool,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBanner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addCustomCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addCustomSection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addNews' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addScrapRate' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addServiceRate' : IDL.Func([IDL.Nat, ServiceRate], [], []),
  'addShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addUdhaarCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
      [],
    ),
  'addUdhaarTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
      [],
    ),
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminAdjustWallet' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminListOfferUsers' : IDL.Func([], [IDL.Vec(OfferUser)], ['query']),
  'adminListPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(OfferWithdrawal)],
      ['query'],
    ),
  'adminResolveWithdrawal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'paid' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'approveProvider' : IDL.Func([IDL.Nat, SubscriptionPlan], [], []),
  'approveTopupRequest' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'changeAdminPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteBanner' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomCode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomSection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteScrapRate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteServiceRate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteUdhaarCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUdhaarTransaction' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'editBanner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'forgotPassword' : IDL.Func([MobileNumber, IDL.Text, IDL.Text], [], []),
  'getActiveBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getActiveProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'getAdminConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'getAllRechargeTransactions' : IDL.Func(
      [],
      [IDL.Vec(RechargeTransaction)],
      ['query'],
    ),
  'getAllToggles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getAllTopupRequests' : IDL.Func(
      [],
      [IDL.Vec(WalletTopupRequest)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllWalletBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getAppSettings' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCommissionConfig' : IDL.Func([], [CommissionConfig], ['query']),
  'getCustomCodes' : IDL.Func([], [IDL.Vec(CustomCode)], ['query']),
  'getCustomSections' : IDL.Func([], [IDL.Vec(CustomSection)], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getJobs' : IDL.Func([], [IDL.Vec(JobItem)], ['query']),
  'getMyOfferTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OfferTransaction)],
      ['query'],
    ),
  'getMyOfferWithdrawals' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OfferWithdrawal)],
      ['query'],
    ),
  'getMyRechargeHistory' : IDL.Func(
      [],
      [IDL.Vec(RechargeTransaction)],
      ['query'],
    ),
  'getMyRechargeReceipts' : IDL.Func([], [IDL.Vec(RechargeReceipt)], ['query']),
  'getMyTopupRequests' : IDL.Func([], [IDL.Vec(WalletTopupRequest)], ['query']),
  'getMyWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getOfferEarningsSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'referralCode' : IDL.Text,
          'pendingEarnings' : IDL.Nat,
          'totalEarnings' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOfferPortalConfig' : IDL.Func([], [OfferPortalConfig], ['query']),
  'getOfferPortalConfigPublic' : IDL.Func(
      [],
      [
        IDL.Record({
          'adminProfitPct' : IDL.Nat,
          'isEnabled' : IDL.Bool,
          'userProfitPct' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getProviderOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getProviderProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProviderProfile)],
      ['query'],
    ),
  'getProvidersByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'getProvidersPendingApproval' : IDL.Func(
      [],
      [IDL.Vec(ProviderProfile)],
      ['query'],
    ),
  'getRecentUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getRechargeApiConfig' : IDL.Func([], [RechargeApiConfig], ['query']),
  'getRechargeReceipt' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RechargeReceipt)],
      ['query'],
    ),
  'getRechargeServiceEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getScrapRates' : IDL.Func([], [IDL.Vec(ScrapRate)], ['query']),
  'getSmsConfig' : IDL.Func([], [SmsConfig], ['query']),
  'getSubscriptionPricing' : IDL.Func(
      [],
      [IDL.Opt(SubscriptionPricing)],
      ['query'],
    ),
  'getUdhaarBalance' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUdhaarCustomers' : IDL.Func([], [IDL.Vec(UdhaarCustomer)], ['query']),
  'getUdhaarTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UdhaarTransaction), 'err' : IDL.Text })],
      ['query'],
    ),
  'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserByMobile' : IDL.Func([MobileNumber], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(VideoItem)], ['query']),
  'getWalletBalanceByUserId' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'initiateRecharge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'login' : IDL.Func([MobileNumber, IDL.Text], [User], []),
  'loginOfferUser' : IDL.Func([IDL.Text, IDL.Text], [OfferUser], []),
  'markUdhaarTransactionPaid' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
      [],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'processCpaLeadPostback' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'refundRecharge' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'registerOfferUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [OfferUser],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, MobileNumber, IDL.Text, UserRole, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'rejectProvider' : IDL.Func([IDL.Nat], [], []),
  'removeShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestOfferWithdrawal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'requestWalletTopup' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setPlanType' : IDL.Func([IDL.Nat, PlanType], [], []),
  'setRechargeServiceEnabled' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'toggleCustomSection' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'updateAdminConfig' : IDL.Func([AdminConfig], [], []),
  'updateAppSettings' : IDL.Func([IDL.Text], [], []),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateCommissionConfig' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateCustomCode' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateCustomSection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateNews' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateOfferPortalConfig' : IDL.Func(
      [IDL.Bool, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProviderProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProviderProfileFull' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateRechargeApiConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateRechargeStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateScrapRate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateSmsConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateSubscriptionPricing' : IDL.Func([SubscriptionPricing], [], []),
  'updateToggle' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateUdhaarCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
      [],
    ),
  'updateUdhaarTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
      [],
    ),
  'updateVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'uploadPaymentScreenshot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceRate = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UdhaarCustomer = IDL.Record({
    'id' : IDL.Text,
    'shopId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UdhaarTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'transactionType' : IDL.Text,
    'shopId' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const OfferUser = IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'pendingEarnings' : IDL.Nat,
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'passwordHash' : IDL.Text,
    'totalEarnings' : IDL.Nat,
  });
  const OfferWithdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'offerUserId' : IDL.Nat,
    'processedAt' : IDL.Opt(IDL.Int),
    'adminNote' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const SubscriptionPlan = IDL.Variant({
    'twelveMonths' : IDL.Null,
    'threeMonths' : IDL.Null,
    'oneMonth' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MobileNumber = IDL.Text;
  const Banner = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'linkUrl' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PlanType = IDL.Variant({
    'pending' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const ProviderProfile = IDL.Record({
    'userId' : IDL.Nat,
    'subscriptionExpiry' : IDL.Opt(IDL.Int),
    'subscriptionPlan' : SubscriptionPlan,
    'description' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'subscriptionStatus' : SubscriptionStatus,
    'paymentScreenshotBlobId' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'serviceRates' : IDL.Vec(ServiceRate),
    'upiId' : IDL.Text,
    'shopName' : IDL.Text,
    'category' : IDL.Text,
    'qrCodeBlobId' : IDL.Opt(IDL.Text),
    'planType' : PlanType,
    'photos' : IDL.Vec(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdminConfig = IDL.Record({
    'email' : IDL.Text,
    'adminName' : IDL.Text,
    'upiId' : IDL.Text,
    'mobile' : MobileNumber,
    'qrCodeBlobId' : ExternalBlob,
  });
  const RechargeTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'netCost' : IDL.Float64,
    'userId' : IDL.Nat,
    'operator' : IDL.Text,
    'createdAt' : IDL.Int,
    'circle' : IDL.Text,
    'commission' : IDL.Float64,
    'mobile' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const WalletTopupRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Nat,
    'note' : IDL.Text,
    'amount' : IDL.Float64,
    'requestedAt' : IDL.Int,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'provider' : IDL.Null,
    'customer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'securityQuestion' : IDL.Text,
    'securityAnswer' : IDL.Text,
    'passwordHash' : IDL.Text,
    'mobile' : MobileNumber,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'mobile' : MobileNumber,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'emoji' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const CommissionConfig = IDL.Record({
    'retailerSharePct' : IDL.Float64,
    'adminSharePct' : IDL.Float64,
    'globalCommissionPct' : IDL.Float64,
  });
  const CustomCode = IDL.Record({
    'id' : IDL.Nat,
    'placement' : IDL.Text,
    'code' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
    'btnLabel' : IDL.Text,
  });
  const CustomSection = IDL.Record({
    'id' : IDL.Nat,
    'placement' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'heading' : IDL.Text,
    'enabled' : IDL.Bool,
    'buttons' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'orderType' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Nat,
    'providerId' : IDL.Nat,
  });
  const JobItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'applyLink' : IDL.Text,
    'createdAt' : IDL.Int,
    'enabled' : IDL.Bool,
    'category' : IDL.Text,
    'department' : IDL.Text,
    'lastDate' : IDL.Text,
    'location' : IDL.Text,
  });
  const OfferTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'reversed' : IDL.Null,
      'credited' : IDL.Null,
    }),
    'offerUserId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'txType' : IDL.Variant({
      'manualCredit' : IDL.Null,
      'referralBonus' : IDL.Null,
      'cpalead' : IDL.Null,
    }),
    'amount' : IDL.Nat,
  });
  const RechargeReceipt = IDL.Record({
    'id' : IDL.Nat,
    'txnId' : IDL.Nat,
    'netCost' : IDL.Nat,
    'userId' : IDL.Nat,
    'operator' : IDL.Text,
    'generatedAt' : IDL.Int,
    'circle' : IDL.Text,
    'referenceId' : IDL.Text,
    'commission' : IDL.Nat,
    'mobile' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const NewsItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'link' : IDL.Text,
    'createdAt' : IDL.Int,
    'enabled' : IDL.Bool,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const OfferPortalConfig = IDL.Record({
    'cpaLeadWebhookSecret' : IDL.Text,
    'adminProfitPct' : IDL.Nat,
    'isEnabled' : IDL.Bool,
    'userProfitPct' : IDL.Nat,
  });
  const RechargeApiConfig = IDL.Record({
    'autoRefundEnabled' : IDL.Bool,
    'isActive' : IDL.Bool,
    'responseParam' : IDL.Text,
    'apiKey' : IDL.Text,
    'apiUrl' : IDL.Text,
  });
  const ScrapRate = IDL.Record({
    'id' : IDL.Nat,
    'ratePerKg' : IDL.Float64,
    'enabled' : IDL.Bool,
    'ratePerGram' : IDL.Float64,
    'itemName' : IDL.Text,
  });
  const SmsConfig = IDL.Record({
    'fast2smsApiKey' : IDL.Text,
    'isEnabled' : IDL.Bool,
    'senderId' : IDL.Text,
  });
  const SubscriptionPricing = IDL.Record({
    'threeMonthPrice' : IDL.Nat,
    'twelveMonthPrice' : IDL.Nat,
    'oneMonthPrice' : IDL.Nat,
  });
  const VideoItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'platform' : IDL.Text,
    'enabled' : IDL.Bool,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addCustomCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addCustomSection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addScrapRate' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addServiceRate' : IDL.Func([IDL.Nat, ServiceRate], [], []),
    'addShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addUdhaarCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
        [],
      ),
    'addUdhaarTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
        [],
      ),
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminAdjustWallet' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminListOfferUsers' : IDL.Func([], [IDL.Vec(OfferUser)], ['query']),
    'adminListPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(OfferWithdrawal)],
        ['query'],
      ),
    'adminResolveWithdrawal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'paid' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'approveProvider' : IDL.Func([IDL.Nat, SubscriptionPlan], [], []),
    'approveTopupRequest' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'changeAdminPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteBanner' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomCode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomSection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteScrapRate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteServiceRate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteUdhaarCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUdhaarTransaction' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'editBanner' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'forgotPassword' : IDL.Func([MobileNumber, IDL.Text, IDL.Text], [], []),
    'getActiveBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getActiveProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
    'getAdminConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
    'getAllRechargeTransactions' : IDL.Func(
        [],
        [IDL.Vec(RechargeTransaction)],
        ['query'],
      ),
    'getAllToggles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getAllTopupRequests' : IDL.Func(
        [],
        [IDL.Vec(WalletTopupRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllWalletBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getAppSettings' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCommissionConfig' : IDL.Func([], [CommissionConfig], ['query']),
    'getCustomCodes' : IDL.Func([], [IDL.Vec(CustomCode)], ['query']),
    'getCustomSections' : IDL.Func([], [IDL.Vec(CustomSection)], ['query']),
    'getCustomerOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getJobs' : IDL.Func([], [IDL.Vec(JobItem)], ['query']),
    'getMyOfferTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OfferTransaction)],
        ['query'],
      ),
    'getMyOfferWithdrawals' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OfferWithdrawal)],
        ['query'],
      ),
    'getMyRechargeHistory' : IDL.Func(
        [],
        [IDL.Vec(RechargeTransaction)],
        ['query'],
      ),
    'getMyRechargeReceipts' : IDL.Func(
        [],
        [IDL.Vec(RechargeReceipt)],
        ['query'],
      ),
    'getMyTopupRequests' : IDL.Func(
        [],
        [IDL.Vec(WalletTopupRequest)],
        ['query'],
      ),
    'getMyWalletBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getOfferEarningsSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'referralCode' : IDL.Text,
            'pendingEarnings' : IDL.Nat,
            'totalEarnings' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOfferPortalConfig' : IDL.Func([], [OfferPortalConfig], ['query']),
    'getOfferPortalConfigPublic' : IDL.Func(
        [],
        [
          IDL.Record({
            'adminProfitPct' : IDL.Nat,
            'isEnabled' : IDL.Bool,
            'userProfitPct' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProviderOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getProviderProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProviderProfile)],
        ['query'],
      ),
    'getProvidersByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'getProvidersPendingApproval' : IDL.Func(
        [],
        [IDL.Vec(ProviderProfile)],
        ['query'],
      ),
    'getRecentUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getRechargeApiConfig' : IDL.Func([], [RechargeApiConfig], ['query']),
    'getRechargeReceipt' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RechargeReceipt)],
        ['query'],
      ),
    'getRechargeServiceEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getScrapRates' : IDL.Func([], [IDL.Vec(ScrapRate)], ['query']),
    'getSmsConfig' : IDL.Func([], [SmsConfig], ['query']),
    'getSubscriptionPricing' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionPricing)],
        ['query'],
      ),
    'getUdhaarBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUdhaarCustomers' : IDL.Func([], [IDL.Vec(UdhaarCustomer)], ['query']),
    'getUdhaarTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UdhaarTransaction), 'err' : IDL.Text })],
        ['query'],
      ),
    'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserByMobile' : IDL.Func([MobileNumber], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(VideoItem)], ['query']),
    'getWalletBalanceByUserId' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'initiateRecharge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'login' : IDL.Func([MobileNumber, IDL.Text], [User], []),
    'loginOfferUser' : IDL.Func([IDL.Text, IDL.Text], [OfferUser], []),
    'markUdhaarTransactionPaid' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'processCpaLeadPostback' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'refundRecharge' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'registerOfferUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [OfferUser],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, MobileNumber, IDL.Text, UserRole, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'rejectProvider' : IDL.Func([IDL.Nat], [], []),
    'removeShopPhoto' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestOfferWithdrawal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'requestWalletTopup' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setPlanType' : IDL.Func([IDL.Nat, PlanType], [], []),
    'setRechargeServiceEnabled' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'toggleCustomSection' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'updateAdminConfig' : IDL.Func([AdminConfig], [], []),
    'updateAppSettings' : IDL.Func([IDL.Text], [], []),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateCommissionConfig' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateCustomCode' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateCustomSection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateNews' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateOfferPortalConfig' : IDL.Func(
        [IDL.Bool, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProviderProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProviderProfileFull' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateRechargeApiConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateRechargeStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateScrapRate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateSmsConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateSubscriptionPricing' : IDL.Func([SubscriptionPricing], [], []),
    'updateToggle' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateUdhaarCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarCustomer, 'err' : IDL.Text })],
        [],
      ),
    'updateUdhaarTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UdhaarTransaction, 'err' : IDL.Text })],
        [],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'uploadPaymentScreenshot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };