/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'email' : string,
  'adminName' : string,
  'upiId' : string,
  'mobile' : MobileNumber,
  'qrCodeBlobId' : ExternalBlob,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AuditAction = { 'SubscriptionRevoke' : null } |
  { 'WalletDeduct' : null } |
  { 'ProviderReject' : null } |
  { 'SubscriptionAssign' : null } |
  { 'WalletAdd' : null } |
  { 'ProviderApprove' : null } |
  { 'FeatureUnlock' : null } |
  { 'FeatureLock' : null };
export interface AuditLogEntry {
  'id' : string,
  'action' : AuditAction,
  'note' : string,
  'timestamp' : bigint,
  'adminEmail' : string,
  'amount' : [] | [bigint],
  'targetUserId' : string,
}
export interface Banner {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'linkUrl' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'subtitle' : string,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'emoji' : string,
  'enabled' : boolean,
}
export interface CommissionConfig {
  'retailerSharePct' : number,
  'adminSharePct' : number,
  'globalCommissionPct' : number,
}
export interface ContentLockerConfig { 'features' : Array<LockedFeature> }
export interface CustomCode {
  'id' : bigint,
  'placement' : string,
  'code' : string,
  'icon' : string,
  'name' : string,
  'enabled' : boolean,
  'btnLabel' : string,
}
export interface CustomSection {
  'id' : bigint,
  'placement' : string,
  'name' : string,
  'createdAt' : bigint,
  'heading' : string,
  'enabled' : boolean,
  'buttons' : string,
}
export type ExternalBlob = Uint8Array;
export interface JobItem {
  'id' : bigint,
  'title' : string,
  'applyLink' : string,
  'createdAt' : bigint,
  'enabled' : boolean,
  'category' : string,
  'department' : string,
  'lastDate' : string,
  'location' : string,
}
export interface LockedFeature {
  'id' : string,
  'createdAt' : bigint,
  'secretKeyHash' : string,
  'cpaOfferLink' : string,
  'updatedAt' : bigint,
  'isLocked' : boolean,
  'featureName' : string,
}
export type MobileNumber = string;
export interface NewsItem {
  'id' : bigint,
  'title' : string,
  'link' : string,
  'createdAt' : bigint,
  'enabled' : boolean,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface OfferPortalConfig {
  'cpaLeadWebhookSecret' : string,
  'cpagripApiKey' : string,
  'adminProfitPct' : bigint,
  'isEnabled' : boolean,
  'userProfitPct' : bigint,
}
export interface OfferTransaction {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'reversed' : null } |
    { 'credited' : null },
  'offerUserId' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'txType' : { 'manualCredit' : null } |
    { 'referralBonus' : null } |
    { 'cpalead' : null },
  'amount' : bigint,
}
export interface OfferUser {
  'id' : bigint,
  'referralCode' : string,
  'userId' : string,
  'createdAt' : bigint,
  'pendingEarnings' : bigint,
  'email' : string,
  'referredBy' : [] | [string],
  'passwordHash' : string,
  'totalEarnings' : bigint,
}
export interface OfferWithdrawal {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'paid' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'offerUserId' : bigint,
  'processedAt' : [] | [bigint],
  'adminNote' : [] | [string],
  'upiId' : string,
  'amount' : bigint,
  'requestedAt' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'orderType' : string,
  'imageUrl' : [] | [string],
  'customerId' : bigint,
  'providerId' : bigint,
}
export type PlanType = { 'pending' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface ProviderProfile {
  'userId' : bigint,
  'subscriptionExpiry' : [] | [bigint],
  'subscriptionPlan' : SubscriptionPlan,
  'description' : string,
  'approvalStatus' : ApprovalStatus,
  'subscriptionStatus' : SubscriptionStatus,
  'paymentScreenshotBlobId' : [] | [string],
  'address' : string,
  'serviceRates' : Array<ServiceRate>,
  'upiId' : string,
  'shopName' : string,
  'category' : string,
  'qrCodeBlobId' : [] | [string],
  'planType' : PlanType,
  'photos' : Array<string>,
}
export interface RechargeApiConfig {
  'autoRefundEnabled' : boolean,
  'isActive' : boolean,
  'responseParam' : string,
  'apiKey' : string,
  'apiUrl' : string,
}
export interface RechargeReceipt {
  'id' : bigint,
  'txnId' : bigint,
  'netCost' : bigint,
  'userId' : bigint,
  'operator' : string,
  'generatedAt' : bigint,
  'circle' : string,
  'referenceId' : string,
  'commission' : bigint,
  'mobile' : string,
  'amount' : bigint,
}
export interface RechargeTransaction {
  'id' : bigint,
  'status' : string,
  'netCost' : number,
  'userId' : bigint,
  'operator' : string,
  'createdAt' : bigint,
  'circle' : string,
  'commission' : number,
  'mobile' : string,
  'amount' : number,
}
export interface ScrapRate {
  'id' : bigint,
  'ratePerKg' : number,
  'enabled' : boolean,
  'ratePerGram' : number,
  'itemName' : string,
}
export interface ServiceRate {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface SmsConfig {
  'fast2smsApiKey' : string,
  'isEnabled' : boolean,
  'senderId' : string,
}
export type SubscriptionPlan = { 'twelveMonths' : null } |
  { 'threeMonths' : null } |
  { 'oneMonth' : null };
export interface SubscriptionPricing {
  'threeMonthPrice' : bigint,
  'twelveMonthPrice' : bigint,
  'oneMonthPrice' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface UdhaarCustomer {
  'id' : string,
  'shopId' : string,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
  'mobile' : string,
}
export interface UdhaarTransaction {
  'id' : string,
  'status' : string,
  'transactionType' : string,
  'shopId' : string,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'customerId' : string,
  'amount' : number,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'securityQuestion' : string,
  'securityAnswer' : string,
  'passwordHash' : string,
  'mobile' : MobileNumber,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'role' : UserRole,
  'mobile' : MobileNumber,
}
export type UserRole = { 'admin' : null } |
  { 'provider' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubscription {
  'status' : string,
  'assignedByAdmin' : boolean,
  'endDate' : bigint,
  'userId' : string,
  'startDate' : bigint,
}
export type VerifyKeyResult = { 'ok' : boolean } |
  { 'err' : string };
export interface VideoItem {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'platform' : string,
  'enabled' : boolean,
  'category' : string,
  'videoUrl' : string,
}
export interface WalletTopupRequest {
  'id' : bigint,
  'status' : string,
  'userId' : bigint,
  'note' : string,
  'amount' : number,
  'requestedAt' : bigint,
  'resolvedAt' : [] | [bigint],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBanner' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addCategory' : ActorMethod<[string, string, string], bigint>,
  'addCustomCode' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'addCustomSection' : ActorMethod<[string, string, string, string], bigint>,
  'addJob' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addNews' : ActorMethod<[string, string, string, string, string], bigint>,
  'addScrapRate' : ActorMethod<[string, number, number], bigint>,
  'addServiceRate' : ActorMethod<[bigint, ServiceRate], undefined>,
  'addShopPhoto' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Add a customer under the calling provider's shop.
   * / shopId is derived from msg.caller — never accepted from the client.
   */
  'addUdhaarCustomer' : ActorMethod<
    [string, string, string],
    { 'ok' : UdhaarCustomer } |
      { 'err' : string }
  >,
  /**
   * / Add a transaction. shopId is derived from caller; customerId must belong to caller.
   */
  'addUdhaarTransaction' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'addVideo' : ActorMethod<[string, string, string, string, string], bigint>,
  /**
   * / Directly add or deduct balance for any user — admin only.
   */
  'adminAdjustWallet' : ActorMethod<[bigint, number, boolean, string], boolean>,
  /**
   * / Adjust (add or deduct) a user's wallet balance and log the action — admin only.
   * / Returns the new balance as Int on success.
   */
  'adminAdjustWalletBalance' : ActorMethod<
    [string, bigint, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Manually assign or revoke a subscription for a user — admin only.
   */
  'adminAssignSubscription' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / List all Offer Portal users — admin only.
   */
  'adminListOfferUsers' : ActorMethod<[], Array<OfferUser>>,
  /**
   * / List all pending withdrawal requests — admin only.
   */
  'adminListPendingWithdrawals' : ActorMethod<[], Array<OfferWithdrawal>>,
  /**
   * / Resolve a withdrawal request (approve/reject/paid) — admin only.
   */
  'adminResolveWithdrawal' : ActorMethod<
    [
      bigint,
      { 'paid' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
      [] | [string],
    ],
    boolean
  >,
  'approveProvider' : ActorMethod<[bigint, SubscriptionPlan], undefined>,
  /**
   * / Approve or reject a topup request.  On approval, funds are credited — admin only.
   */
  'approveTopupRequest' : ActorMethod<[bigint, boolean], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'changeAdminPin' : ActorMethod<[string, string], undefined>,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteCustomCode' : ActorMethod<[bigint], boolean>,
  'deleteCustomSection' : ActorMethod<[bigint], boolean>,
  'deleteJob' : ActorMethod<[bigint], boolean>,
  'deleteNews' : ActorMethod<[bigint], boolean>,
  'deleteScrapRate' : ActorMethod<[bigint], boolean>,
  'deleteServiceRate' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Delete a customer and all its transactions. Caller must own the customer.
   */
  'deleteUdhaarCustomer' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Delete a transaction. Caller must own the transaction.
   */
  'deleteUdhaarTransaction' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteVideo' : ActorMethod<[bigint], boolean>,
  'editBanner' : ActorMethod<
    [bigint, string, string, string, string, boolean, bigint],
    undefined
  >,
  'forgotPassword' : ActorMethod<[MobileNumber, string, string], undefined>,
  'getActiveBanners' : ActorMethod<[], Array<Banner>>,
  'getActiveProviders' : ActorMethod<[], Array<ProviderProfile>>,
  /**
   * / Return the most recent `limit` audit log entries — admin only.
   */
  'getAdminAuditLog' : ActorMethod<[bigint], Array<AuditLogEntry>>,
  'getAdminConfig' : ActorMethod<[], [] | [AdminConfig]>,
  'getAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  /**
   * / Return all recharge transactions (master log) — admin only.
   */
  'getAllRechargeTransactions' : ActorMethod<[], Array<RechargeTransaction>>,
  'getAllToggles' : ActorMethod<[], Array<[string, boolean]>>,
  /**
   * / Return all pending topup requests — admin only.
   */
  'getAllTopupRequests' : ActorMethod<[], Array<WalletTopupRequest>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Return all wallet balances as (userId, balance) pairs — admin only.
   */
  'getAllWalletBalances' : ActorMethod<[], Array<[bigint, number]>>,
  'getAppSettings' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  /**
   * / Return the current commission config — public.
   */
  'getCommissionConfig' : ActorMethod<[], CommissionConfig>,
  /**
   * / Return the full content-locker configuration (all features).
   */
  'getContentLockerConfig' : ActorMethod<[], ContentLockerConfig>,
  'getCustomCodes' : ActorMethod<[], Array<CustomCode>>,
  'getCustomSections' : ActorMethod<[], Array<CustomSection>>,
  'getCustomerOrders' : ActorMethod<[bigint], Array<Order>>,
  'getJobs' : ActorMethod<[], Array<JobItem>>,
  /**
   * / Get Offer Portal transaction history for a user.
   */
  'getMyOfferTransactions' : ActorMethod<[bigint], Array<OfferTransaction>>,
  /**
   * / Get withdrawal requests for an Offer Portal user.
   */
  'getMyOfferWithdrawals' : ActorMethod<[bigint], Array<OfferWithdrawal>>,
  /**
   * / Return the caller's recharge transaction history.
   */
  'getMyRechargeHistory' : ActorMethod<[], Array<RechargeTransaction>>,
  /**
   * / Get all receipts for the calling user.
   */
  'getMyRechargeReceipts' : ActorMethod<[], Array<RechargeReceipt>>,
  /**
   * / Return all topup requests submitted by the caller.
   */
  'getMyTopupRequests' : ActorMethod<[], Array<WalletTopupRequest>>,
  /**
   * / Return the caller's wallet balance (0.0 if no wallet yet).
   */
  'getMyWalletBalance' : ActorMethod<[], number>,
  'getNews' : ActorMethod<[], Array<NewsItem>>,
  /**
   * / Get earnings summary for an Offer Portal user.
   */
  'getOfferEarningsSummary' : ActorMethod<
    [bigint],
    {
      'referralCode' : string,
      'pendingEarnings' : bigint,
      'totalEarnings' : bigint,
    }
  >,
  /**
   * / Get Offer Portal global config — admin only.
   */
  'getOfferPortalConfig' : ActorMethod<[], OfferPortalConfig>,
  /**
   * / Get Offer Portal global config — public (no auth required).
   * / Returns the config so any visitor can check whether the portal is enabled
   * / before showing the login/signup UI.  Webhook secrets are NOT included
   * / in this method — admin-only fields remain protected via getOfferPortalConfig.
   */
  'getOfferPortalConfigPublic' : ActorMethod<
    [],
    {
      'adminProfitPct' : bigint,
      'isEnabled' : boolean,
      'userProfitPct' : bigint,
    }
  >,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[bigint, string], Array<Order>>,
  /**
   * / Alias for getProvidersPendingApproval — kept for frontend compatibility.
   */
  'getPendingApprovals' : ActorMethod<[], Array<ProviderProfile>>,
  'getProviderOrders' : ActorMethod<[bigint], Array<Order>>,
  'getProviderProfile' : ActorMethod<[bigint], [] | [ProviderProfile]>,
  'getProvidersByCategory' : ActorMethod<[string], Array<ProviderProfile>>,
  'getProvidersPendingApproval' : ActorMethod<[], Array<ProviderProfile>>,
  'getRecentUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Return the current recharge API config — admin only.
   */
  'getRechargeApiConfig' : ActorMethod<[], RechargeApiConfig>,
  /**
   * / Get receipt for a specific recharge transaction.
   */
  'getRechargeReceipt' : ActorMethod<[bigint], [] | [RechargeReceipt]>,
  /**
   * / Return whether recharge service is enabled — public.
   */
  'getRechargeServiceEnabled' : ActorMethod<[], boolean>,
  'getScrapRates' : ActorMethod<[], Array<ScrapRate>>,
  /**
   * / Get SMS (Fast2SMS) config — admin only.
   */
  'getSmsConfig' : ActorMethod<[], SmsConfig>,
  'getSubscriptionPricing' : ActorMethod<[], [] | [SubscriptionPricing]>,
  /**
   * / Return balance for a customer. Caller must own the customer.
   */
  'getUdhaarBalance' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  /**
   * / Return only customers belonging to the calling provider.
   * / shopId is derived from msg.caller — no user-supplied filter accepted.
   */
  'getUdhaarCustomers' : ActorMethod<[], Array<UdhaarCustomer>>,
  /**
   * / Return transactions for a customer. Caller must own the customer.
   */
  'getUdhaarTransactions' : ActorMethod<
    [string],
    { 'ok' : Array<UdhaarTransaction> } |
      { 'err' : string }
  >,
  'getUserById' : ActorMethod<[bigint], [] | [User]>,
  'getUserByMobile' : ActorMethod<[MobileNumber], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get the current subscription status for a given user.
   */
  'getUserSubscriptionStatus' : ActorMethod<[string], [] | [UserSubscription]>,
  'getUsersByRole' : ActorMethod<[UserRole], Array<User>>,
  'getVideos' : ActorMethod<[], Array<VideoItem>>,
  /**
   * / Return wallet balance for any userId — admin only.
   */
  'getWalletBalanceByUserId' : ActorMethod<[bigint], number>,
  /**
   * / Initiate a mobile recharge.  Auto-calculates commission; deducts netCost
   * / from caller's wallet.  Returns new transaction ID.
   */
  'initiateRecharge' : ActorMethod<[string, string, string, number], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'login' : ActorMethod<[MobileNumber, string], User>,
  /**
   * / Login to the Offer Portal.
   */
  'loginOfferUser' : ActorMethod<[string, string], OfferUser>,
  /**
   * / Mark a transaction as paid. Caller must own the transaction.
   */
  'markUdhaarTransactionPaid' : ActorMethod<
    [string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    bigint
  >,
  /**
   * / Process a CPALead postback: verify secret, split profit, credit earnings.
   * / Also triggers 1% referral bonus to the referrer if any.
   */
  'processCpaLeadPostback' : ActorMethod<[bigint, bigint, string], boolean>,
  /**
   * / Refund a Failed recharge — restores netCost to user wallet — admin only.
   */
  'refundRecharge' : ActorMethod<[bigint], boolean>,
  /**
   * / Register a new Offer Portal user (isolated from main user DB).
   * / Returns the full OfferUser record so the frontend can auto-login
   * / immediately after signup without a second round-trip.
   */
  'registerOfferUser' : ActorMethod<[string, string, [] | [string]], OfferUser>,
  'registerUser' : ActorMethod<
    [string, MobileNumber, string, UserRole, string, string],
    undefined
  >,
  'rejectProvider' : ActorMethod<[bigint], undefined>,
  /**
   * / Remove a locked feature by id — admin only.
   */
  'removeLockedFeature' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeShopPhoto' : ActorMethod<[bigint, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  /**
   * / Submit a UPI withdrawal request from the Offer Portal.
   */
  'requestOfferWithdrawal' : ActorMethod<[bigint, string, bigint], bigint>,
  /**
   * / Request admin to top-up your wallet.  Returns the new request ID.
   */
  'requestWalletTopup' : ActorMethod<[number, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<User>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Create or update a locked feature — admin only.
   */
  'setLockedFeature' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setPlanType' : ActorMethod<[bigint, PlanType], undefined>,
  /**
   * / Enable or disable the recharge service — admin only.
   */
  'setRechargeServiceEnabled' : ActorMethod<[boolean], boolean>,
  'toggleCustomSection' : ActorMethod<[bigint, boolean], boolean>,
  'updateAdminConfig' : ActorMethod<[AdminConfig], undefined>,
  'updateAppSettings' : ActorMethod<[string], undefined>,
  'updateCategory' : ActorMethod<
    [bigint, string, string, string, boolean],
    boolean
  >,
  /**
   * / Update commission config — admin only.
   * / Validates: retailerPct + adminPct must equal globalPct.
   */
  'updateCommissionConfig' : ActorMethod<[number, number, number], boolean>,
  'updateCustomCode' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  'updateCustomSection' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    boolean
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean],
    boolean
  >,
  'updateNews' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  /**
   * / Update Offer Portal config (toggle, offer wall secret, profit split) — admin only.
   * / Returns #ok(true) on success, #err(reason) if validation fails (e.g. API key too short).
   */
  'updateOfferPortalConfig' : ActorMethod<
    [boolean, string, string, bigint, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProviderProfile' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  /**
   * / Extended updateProviderProfile to include upiId and qrCodeBlobId
   */
  'updateProviderProfileFull' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [string]],
    undefined
  >,
  /**
   * / Save recharge API config — admin only.
   */
  'updateRechargeApiConfig' : ActorMethod<
    [string, string, string, boolean, boolean],
    boolean
  >,
  /**
   * / Update the status of a recharge transaction — admin only.
   * / Auto-refund: if status = "Failed" and autoRefundEnabled, automatically refunds netCost.
   * / Receipt: if status = "Success", generates a digital receipt.
   * / SMS: if smsConfig.isEnabled, sends an alert (fire-and-forget).
   */
  'updateRechargeStatus' : ActorMethod<[bigint, string], boolean>,
  'updateScrapRate' : ActorMethod<
    [bigint, string, number, number, boolean],
    boolean
  >,
  /**
   * / Update SMS config — admin only.
   */
  'updateSmsConfig' : ActorMethod<[string, string, boolean], boolean>,
  'updateSubscriptionPricing' : ActorMethod<[SubscriptionPricing], undefined>,
  'updateToggle' : ActorMethod<[string, boolean], undefined>,
  /**
   * / Update a customer. Caller must own the customer (shopId check).
   */
  'updateUdhaarCustomer' : ActorMethod<
    [string, string, string, string],
    { 'ok' : UdhaarCustomer } |
      { 'err' : string }
  >,
  /**
   * / Update a transaction. Caller must own the transaction (shopId check).
   */
  'updateUdhaarTransaction' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'updateVideo' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  'uploadPaymentScreenshot' : ActorMethod<[bigint, string], undefined>,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
  /**
   * / User-facing: verify a plain-text unlock key for a named feature.
   */
  'verifyUnlockKey' : ActorMethod<[string, string], VerifyKeyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];